/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/crystal_1.glb 
*/

import { useGLTF } from '@react-three/drei'
import React, { forwardRef } from 'react'

export const Crystal1 = forwardRef(function(props, Cry) {
  const { nodes, materials } = useGLTF('./Models/crystal_1.glb')



  return (
    <group {...props} ref={props.Cry} position={[65, 7, -14]} rotation={[0, 0, 0.33]} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} scale={8.963} />
    </group>
  )
})

useGLTF.preload('./Models/crystal_1.glb')
