/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/crystal_round.glb 
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three';
import gsap from 'gsap'
import React, { useEffect, useLayoutEffect, useRef } from 'react'
import { Crystal1 } from './Crystal_1'
import { Crystal2 } from './Crystal_2'
import { CrystalP } from './Crystal_parts'

export function Crystal(props) {
  const { nodes, materials } = useGLTF('./Models/crystal_round.glb')

  const ref = useRef()
  const crystalRef = useRef()
  const Cry = useRef()
  const Cry2 = useRef()
  const CryP = useRef()
  const CryP1 = useRef()
  const CryP2 = useRef()
  const CryP3 = useRef()
  const CryP4 = useRef()
  const CryP5 = useRef()
  const CryP6 = useRef()
  const CryP7 = useRef()
  const CryP8 = useRef()
  const CryP9 = useRef()
  const CryP10 = useRef()
  const CryP11 = useRef()
  const CryP12 = useRef()
  const CryP13 = useRef()
  const tl = useRef()
  const tl2 = useRef()
  const CryRef = useRef()


  const ScreenX = window.innerWidth
  const ScreenY = window.innerHeight
  
  const Mousetrack = (e) => {
    const MouseX = e.clientX
    const MouseY = e.clientY
  
    // ROTATE THE CRYSTALS ACCOORDING TO THE MOUSE MOVEMENT
    const CalcValX = ((2*MouseX)/ScreenX)-1
    console.log(CalcValX)
    CryRef.current.rotation.y = 0.005*CalcValX
    // CryRef.current.rotation.z = -0.005*CalcValX
  
  
  
    // console.log(e.clientX, e.clientY);
  }
  useEffect(() => {
    window.addEventListener("mousemove",Mousetrack)
  
    return () => {
      window.removeEventListener("mousemove", Mousetrack)
    }
  })

  useFrame(() => {
    const scrollTop = window.scrollY;
    const scrollHeight = document.documentElement.scrollHeight - window.innerHeight;
    
    // Calculate scroll position in the range of 0 to 1
    const scrollOffset = scrollTop / scrollHeight;

    tl.current.seek(scrollOffset * tl.current.duration())
    tl2.current.seek(scrollOffset * tl2.current.duration())
// console.log();

    
  })

  for (let i in nodes) {
    
    // Create a new MeshPhongMaterial
if(nodes[i].material) {
  const phongMaterial = new THREE.MeshPhongMaterial({
    color: nodes[i].material.color, // Set color
    specular: "#9e00c6", // Set specular color
    shininess: 100, // Set shininess (if needed)
    emissive:"#10001B",
    // Set any other properties specific to MeshPhongMaterial as needed
  });
  nodes[i].material = phongMaterial;
  console.log(nodes[i]);
}

    // Set the material of the node to the new MeshPhongMaterial
}
  useLayoutEffect(() => {
    tl.current = gsap.timeline({duration:14});
    tl2.current = gsap.timeline({duration:14});
    // PART 1 ROTATION OF MAIN GROUP
    tl.current.to(ref.current.rotation, {duration:1, y:0,},0)
    tl.current.to(ref.current.position, {duration:1, z:50,},0)
    // PART 2 PAN AND ROTATION OF MAIN GROUP
    tl.current.to(ref.current.position, {duration:1, z:110,},1)
    tl.current.to(ref.current.rotation, {duration:0.95, x:1, ease:"power1.in"},1.05)
    // PART 3 CRYSTAL 1 ANIMATION IN AND OUT
    tl.current.to(Cry.current.position, {duration:1.2, x:28,y:-14,z:-21,},1.1)
    tl.current.to(Cry.current.rotation, {duration:1.2, x:-1.3,y:8,z:0.1,},1.1)
    tl.current.to(Cry.current.rotation, {duration:1, x:0,y:0,z:0.33},2.3)
    tl.current.to(Cry.current.position, {duration:1, x:65,y:7,z:-14},2.3)
    // PART 4 CRYTSTAL 2 ANIMATION IN AND OUT
    tl.current.to(Cry2.current.position, {duration:0.8, x:-14,y:7,z:-14},2.6)
    tl.current.to(Cry2.current.rotation, {duration:0.1, x:-1.4,y:0,z:1.35},2.6)
    tl.current.to(Cry2.current.rotation, {duration:0.7, x:-1.4,y:0,z:0},2.7)
    tl.current.to(Cry2.current.position, {duration:1, x:-70,y:7,z:14},3.4)
    tl.current.to(Cry2.current.rotation, {duration:1, x:0,y:0,z:0, ease:"power1.in"},3.4)
    // PART 5 ZOOM OUT ANIMAITON OF MAIN GROUP
    tl.current.to(ref.current.position, {duration:3.5, y:-100,z:-350, ease:"power1.in"},3.5)
    tl.current.to(ref.current.position, {duration:2.5, y:-230,z:-1080},7)
    tl.current.to(ref.current.rotation, {duration:6, y:0.2},3.5)

    // PART 6 FRAGMENTED CRYSTAL
    tl2.current.to(CryP.current.rotation, {duration:14, x:3,y:0,z:0.5},0)

    tl2.current.from(CryP1.current.position, {duration:3, x:-70,y:7,z:14},5)
    tl2.current.from(CryP2.current.position, {duration:3, x:-50,y:17,z:14},5)
    tl2.current.from(CryP3.current.position, {duration:3, x:-30,y:32,z:24},5)
    tl2.current.from(CryP4.current.position, {duration:3, x:-10,y:50,z:17},5)
    tl2.current.from(CryP5.current.position, {duration:3, x:0,y:45,z:36},5)
    tl2.current.from(CryP6.current.position, {duration:3, x:76,y:14,z:54},5)
    tl2.current.from(CryP7.current.position, {duration:3, x:25,y:11,z:5},5)
    tl2.current.from(CryP8.current.position, {duration:3, x:0,y:61,z:10},5)
    tl2.current.from(CryP9.current.position, {duration:3, x:63,y:1,z:0},5)
    tl2.current.from(CryP10.current.position, {duration:3, x:16,y:41,z:0},5)
    tl2.current.from(CryP11.current.position, {duration:3, x:73,y:11,z:61},5)
    tl2.current.from(CryP12.current.position, {duration:3, x:16,y:11,z:10},5)
    tl2.current.from(CryP13.current.position, {duration:3, x:77,y:15,z:34},5)


    tl2.current.from(CryP1.current.rotation, {duration:3, x:0,y:1,z:0},5)
    tl2.current.from(CryP2.current.rotation, {duration:3, x:0,y:1,z:0},5)
    tl2.current.from(CryP3.current.rotation, {duration:3, x:0,y:1,z:0},5)
    tl2.current.from(CryP4.current.rotation, {duration:3, x:0,y:1,z:0},5)
    tl2.current.from(CryP5.current.rotation, {duration:3, x:0,y:1,z:0},5)
    tl2.current.from(CryP6.current.rotation, {duration:3, x:0,y:0,z:0},5)
    tl2.current.from(CryP7.current.rotation, {duration:3, x:0,y:0,z:0},5)
    tl2.current.from(CryP8.current.rotation, {duration:3, x:0,y:0,z:0},5)
    tl2.current.from(CryP9.current.rotation, {duration:3, x:0,y:0,z:0},5)
    tl2.current.from(CryP10.current.rotation, {duration:3, x:0,y:0,z:0},5)
   tl2.current.from(CryP12.current.rotation, {duration:3, x:0,y:0,z:0},5)
   tl2.current.from(CryP13.current.rotation, {duration:3, x:0,y:0,z:0},5)
   
   
   tl2.current.to(CryP.current.position, {duration:0.8, x:0,y:30,z:170},8)

    
  },[])

  return (
    <>
    <group ref={CryRef}>
    <group {...props} dispose={null} rotation={[0,1.6,0]} position={[0,0,0]} ref={ref}>
      
      <mesh ref={crystalRef} geometry={nodes.Cylinder100.geometry} material={nodes.Cylinder100.material} type='MeshPhongMaterial' position={[102.066, 7.416, -0.523]} rotation={[0.82, 0.889, -0.744]} scale={[3.165, 8.223, 3.165]} />
      <mesh geometry={nodes.Cylinder101.geometry} material={nodes.Cylinder101.material} type='MeshPhongMaterial' position={[-76.785, 9.442, 114.255]} rotation={[0.126, 0.579, -0.192]} scale={[3.608, 9.374, 3.608]} />
      <mesh geometry={nodes.Cylinder102.geometry} material={nodes.Cylinder102.material} type='MeshPhongMaterial' position={[-30.016, 5.057, 104.403]} rotation={[-0.574, -0.686, -0.637]} scale={[2.256, 5.861, 2.256]} />
      <mesh geometry={nodes.Cylinder103.geometry} material={nodes.Cylinder103.material} type='MeshPhongMaterial' position={[-39.121, 4.429, 53.125]} rotation={[-0.109, 0.125, 0.289]} scale={[2.341, 6.082, 2.341]} />
      <mesh geometry={nodes.Cylinder104.geometry} material={nodes.Cylinder104.material} type='MeshPhongMaterial' position={[50.081, 4.387, 55.347]} rotation={[0.582, -1.239, 0.088]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Cylinder105.geometry} material={nodes.Cylinder105.material} type='MeshPhongMaterial' position={[47.175, 6.394, 100.676]} rotation={[-0.271, 0.984, -0.107]} scale={[3.633, 9.44, 3.633]} />
      <mesh geometry={nodes.Cylinder106.geometry} material={nodes.Cylinder106.material} type='MeshPhongMaterial' position={[19.015, 4.042, 76.441]} rotation={[0.436, 0.031, -0.182]} scale={[2.657, 6.904, 2.657]} />
      <mesh geometry={nodes.Cylinder107.geometry} material={nodes.Cylinder107.material} type='MeshPhongMaterial' position={[-5.578, 1.323, 145.673]} rotation={[2.484, -1.227, 2.673]} scale={[1.709, 4.44, 1.709]} />
      <mesh geometry={nodes.Cylinder108.geometry} material={nodes.Cylinder108.material} type='MeshPhongMaterial' position={[-8.712, 2.113, 147.815]} rotation={[-3.096, 0.31, 3.023]} scale={[1.086, 2.821, 1.086]} />
      <mesh geometry={nodes.Cylinder109.geometry} material={nodes.Cylinder109.material} type='MeshPhongMaterial' position={[21.731, 2.113, 148.814]} rotation={[-3.096, 0.31, 3.023]} scale={[1.086, 2.821, 1.086]} />
      <mesh geometry={nodes.Cylinder110.geometry} material={nodes.Cylinder110.material} type='MeshPhongMaterial' position={[74.661, 4.1, 2.792]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder111.geometry} material={nodes.Cylinder111.material} type='MeshPhongMaterial' position={[83.829, 8.142, 21.366]} rotation={[-0.224, -0.148, 0.108]} scale={[4.31, 9.176, 4.417]} />
      <mesh geometry={nodes.Cylinder112.geometry} material={nodes.Cylinder112.material} type='MeshPhongMaterial' position={[69.154, 2.937, 9.836]} rotation={[0.122, 0.191, -0.263]} scale={[1.69, 3.598, 1.732]} />
      <mesh geometry={nodes.Cylinder113.geometry} material={nodes.Cylinder113.material} type='MeshPhongMaterial' position={[-1.092, 1.303, -1.202]} rotation={[0.122, 0.191, -0.263]} scale={[0.61, 0.235, 0.362]} />
      <mesh geometry={nodes.Cylinder114.geometry} material={nodes.Cylinder114.material} type='MeshPhongMaterial' position={[66.131, 1.303, -2.767]} rotation={[1.829, 0.316, 1.227]} scale={[1.785, 1.685, 1.038]} />
      <mesh geometry={nodes.Cylinder115.geometry} material={nodes.Cylinder115.material} type='MeshPhongMaterial' position={[96.283, 2.937, 18.431]} rotation={[0.122, 0.191, -0.263]} scale={[1.69, 3.598, 1.732]} />
      <mesh geometry={nodes.Cylinder116.geometry} material={nodes.Cylinder116.material} type='MeshPhongMaterial' position={[90.144, 4.237, 18.431]} rotation={[0.154, -0.355, 0.275]} scale={[-3.327, -7.083, -3.41]} />
      <mesh geometry={nodes.Cylinder117.geometry} material={nodes.Cylinder117.material} type='MeshPhongMaterial' position={[68.899, 8.142, 22.457]} rotation={[-2.998, -0.006, 0.319]} scale={[4.31, 9.176, 4.417]} />
      <mesh geometry={nodes.Cylinder118.geometry} material={nodes.Cylinder118.material} type='MeshPhongMaterial' position={[119.632, 8.142, -1.257]} rotation={[-2.998, -0.006, 0.319]} scale={[4.31, 9.176, 4.417]} />
      <mesh geometry={nodes.Cylinder119.geometry} material={nodes.Cylinder119.material} type='MeshPhongMaterial' position={[-87.582, 8.142, 11.14]} rotation={[2.623, -0.832, -0.503]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder120.geometry} material={nodes.Cylinder120.material} type='MeshPhongMaterial' position={[87.668, 8.278, -34.901]} rotation={[-0.731, 0.811, 0.576]} scale={[5.037, 13.086, 5.037]} />
      <mesh geometry={nodes.Cylinder121.geometry} material={nodes.Cylinder121.material} type='MeshPhongMaterial' position={[129.46, 5.753, -40.081]} rotation={[0.154, -0.355, 0.275]} scale={[-3.327, -7.083, -3.41]} />
      <mesh geometry={nodes.Cylinder122.geometry} material={nodes.Cylinder122.material} type='MeshPhongMaterial' position={[136.199, 2.415, 13.486]} rotation={[0.027, 0.415, 0.269]} scale={[1.116, 2.899, 1.116]} />
      <mesh geometry={nodes.Cylinder123.geometry} material={nodes.Cylinder123.material} type='MeshPhongMaterial' position={[134.369, 2.937, 3.423]} rotation={[0.122, 0.191, -0.263]} scale={[1.376, 2.931, 1.411]} />
      <mesh geometry={nodes.Cylinder124.geometry} material={nodes.Cylinder124.material} type='MeshPhongMaterial' position={[73.474, 4.1, -27.372]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder125.geometry} material={nodes.Cylinder125.material} type='MeshPhongMaterial' position={[69.48, 4.1, -44.026]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder126.geometry} material={nodes.Cylinder126.material} type='MeshPhongMaterial' position={[67.955, 5.775, -35.195]} scale={[3.414, 7.268, 3.499]} />
      <mesh geometry={nodes.Cylinder127.geometry} material={nodes.Cylinder127.material} type='MeshPhongMaterial' position={[152.043, 2.415, 39.2]} rotation={[0.027, 0.415, 0.269]} scale={[0.924, 2.402, 0.924]} />
      <mesh geometry={nodes.Cylinder128.geometry} material={nodes.Cylinder128.material} type='MeshPhongMaterial' position={[137.196, 2.937, 35.218]} rotation={[0.122, 0.191, -0.263]} scale={[1.582, 3.367, 1.621]} />
      <mesh geometry={nodes.Cylinder129.geometry} material={nodes.Cylinder129.material} type='MeshPhongMaterial' position={[131.293, 2.415, 40.149]} rotation={[-0.081, 0.29, -0.081]} scale={[0.955, 2.482, 0.955]} />
      <mesh geometry={nodes.Cylinder130.geometry} material={nodes.Cylinder130.material} type='MeshPhongMaterial' position={[134.324, 1.584, 24.807]} rotation={[-0.151, 0.16, -0.433]} scale={[0.956, 2.036, 0.98]} />
      <mesh geometry={nodes.Cylinder131.geometry} material={nodes.Cylinder131.material} type='MeshPhongMaterial' position={[155.847, 1.584, 2.095]} rotation={[2.982, 0.94, -0.251]} scale={[0.956, 2.036, 0.98]} />
      <mesh geometry={nodes.Cylinder132.geometry} material={nodes.Cylinder132.material} type='MeshPhongMaterial' position={[-89.495, 10.546, 24.98]} rotation={[0.169, -0.926, 0.34]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder133.geometry} material={nodes.Cylinder133.material} type='MeshPhongMaterial' position={[-92.838, 10.546, 22.012]} rotation={[0.152, 0.841, 0.091]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder134.geometry} material={nodes.Cylinder134.material} type='MeshPhongMaterial' position={[-81.455, 10.546, 37.942]} rotation={[-0.418, 0.253, 0.239]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder135.geometry} material={nodes.Cylinder135.material} type='MeshPhongMaterial' position={[-76.714, 7.347, 53.574]} rotation={[0.186, -0.236, 0.394]} scale={[2.904, 7.546, 2.904]} />
      <mesh geometry={nodes.Cylinder136.geometry} material={nodes.Cylinder136.material} type='MeshPhongMaterial' position={[-89.495, 10.546, 45.632]} rotation={[-0.177, -1.08, 0.171]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder137.geometry} material={nodes.Cylinder137.material} type='MeshPhongMaterial' position={[-65.637, 4.733, 54.826]} rotation={[-0.181, 0.068, -0.327]} scale={[2.802, 5.965, 2.872]} />
      <mesh geometry={nodes.Cylinder138.geometry} material={nodes.Cylinder138.material} type='MeshPhongMaterial' position={[-91.481, 10.911, 59.93]} rotation={[-0.042, -1.195, 0.229]} scale={[3.062, 7.957, 3.062]} />
      <mesh geometry={nodes.Cylinder139.geometry} material={nodes.Cylinder139.material} type='MeshPhongMaterial' position={[-87.813, 10.625, 52.854]} rotation={[-0.282, -0.534, -0.34]} scale={[3.446, 8.954, 3.446]} />
      <mesh geometry={nodes.Cylinder140.geometry} material={nodes.Cylinder140.material} type='MeshPhongMaterial' position={[-88.831, 4.733, 57.263]} rotation={[-0.181, 0.068, -0.327]} scale={[2.802, 5.965, 2.872]} />
      <mesh geometry={nodes.Cylinder141.geometry} material={nodes.Cylinder141.material} type='MeshPhongMaterial' position={[22.185, 5.775, -104.364]} scale={[3.414, 7.268, 3.499]} />
      <mesh geometry={nodes.Cylinder142.geometry} material={nodes.Cylinder142.material} type='MeshPhongMaterial' position={[23.71, 4.1, -113.195]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder143.geometry} material={nodes.Cylinder143.material} type='MeshPhongMaterial' position={[27.703, 4.1, -96.541]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder144.geometry} material={nodes.Cylinder144.material} type='MeshPhongMaterial' position={[27.549, 6.452, -88.652]} rotation={[0.27, -1.045, -0.081]} scale={[3.184, 8.272, 3.184]} />
      <mesh geometry={nodes.Cylinder145.geometry} material={nodes.Cylinder145.material} type='MeshPhongMaterial' position={[20.649, 4.035, -93.708]} rotation={[-0.583, 0.605, 0.775]} scale={[2.381, 6.187, 2.381]} />
      <mesh geometry={nodes.Cylinder146.geometry} material={nodes.Cylinder146.material} type='MeshPhongMaterial' position={[13.166, 3.083, -88.4]} rotation={[0.101, -0.611, 0.621]} scale={[1.176, 3.056, 1.176]} />
      <mesh geometry={nodes.Cylinder147.geometry} material={nodes.Cylinder147.material} type='MeshPhongMaterial' position={[21.181, 9.782, -101.524]} rotation={[0.014, 0.712, 0.11]} scale={[3.594, 9.338, 3.594]} />
      <mesh geometry={nodes.Cylinder148.geometry} material={nodes.Cylinder148.material} type='MeshPhongMaterial' position={[-54.185, 4.042, -77.481]} rotation={[0.436, 0.031, -0.182]} scale={[2.657, 6.904, 2.657]} />
      <mesh geometry={nodes.Cylinder149.geometry} material={nodes.Cylinder149.material} type='MeshPhongMaterial' position={[-53.143, 2.081, -95.464]} rotation={[-0.543, -0.383, 0.376]} scale={[-0.566, -1.47, -0.566]} />
      <mesh geometry={nodes.Cylinder150.geometry} material={nodes.Cylinder150.material} type='MeshPhongMaterial' position={[-50.948, 4.48, -99.97]} rotation={[-0.44, 0.73, -0.11]} scale={[1.151, 2.991, 1.151]} />
      <mesh geometry={nodes.Cylinder151.geometry} material={nodes.Cylinder151.material} type='MeshPhongMaterial' position={[-61.891, 2.881, -97.185]} rotation={[-0.501, -0.387, 0.243]} scale={[-0.618, -1.606, -0.618]} />
      <mesh geometry={nodes.Cylinder152.geometry} material={nodes.Cylinder152.material} type='MeshPhongMaterial' position={[-63.023, 4.182, -97.23]} rotation={[0.42, -0.605, -0.143]} scale={[0.439, 1.141, 0.439]} />
      <mesh geometry={nodes.Cylinder153.geometry} material={nodes.Cylinder153.material} type='MeshPhongMaterial' position={[-56.826, 3.918, -99.384]} rotation={[-0.066, -0.169, 0.595]} scale={[1.392, 3.616, 1.392]} />
      <mesh geometry={nodes.Cylinder154.geometry} material={nodes.Cylinder154.material} type='MeshPhongMaterial' position={[-64.964, 5.331, -93.367]} rotation={[-0.061, 0.472, 0.658]} scale={[1.348, 3.501, 1.348]} />
      <mesh geometry={nodes.Cylinder155.geometry} material={nodes.Cylinder155.material} type='MeshPhongMaterial' position={[-53.452, 8.175, -86.054]} rotation={[0.119, -0.746, 0.532]} scale={[3.928, 10.205, 3.928]} />
      <mesh geometry={nodes.Cylinder156.geometry} material={nodes.Cylinder156.material} type='MeshPhongMaterial' position={[-49.171, 5.469, -86.521]} rotation={[0.02, -0.506, -0.59]} scale={[2.923, 7.596, 2.923]} />
      <mesh geometry={nodes.Cylinder157.geometry} material={nodes.Cylinder157.material} type='MeshPhongMaterial' position={[112.511, 4.387, -22.753]} rotation={[0.582, -1.239, 0.088]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Cylinder158.geometry} material={nodes.Cylinder158.material} type='MeshPhongMaterial' position={[107.454, 2.709, -18.794]} rotation={[0.451, 0.838, -0.82]} scale={[2.411, 6.264, 2.411]} />
      <mesh geometry={nodes.Cylinder159.geometry} material={nodes.Cylinder159.material} type='MeshPhongMaterial' position={[101.458, 1.632, -29.71]} rotation={[-0.077, 0.418, 0.703]} scale={[0.364, 0.945, 0.364]} />
      <mesh geometry={nodes.Cylinder160.geometry} material={nodes.Cylinder160.material} type='MeshPhongMaterial' position={[103.777, 4.387, -25.221]} rotation={[0.846, -0.887, 0.164]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Cylinder161.geometry} material={nodes.Cylinder161.material} type='MeshPhongMaterial' position={[109.057, 3.093, -21.281]} rotation={[0.379, 0.143, -0.773]} scale={[-0.507, -1.317, -0.507]} />
      <mesh geometry={nodes.Cylinder162.geometry} material={nodes.Cylinder162.material} type='MeshPhongMaterial' position={[80.713, 9.782, 46.785]} rotation={[0.014, 0.712, 0.11]} scale={[3.594, 9.338, 3.594]} />
      <mesh geometry={nodes.Cylinder163.geometry} material={nodes.Cylinder163.material} type='MeshPhongMaterial' position={[72.697, 3.083, 59.91]} rotation={[0.101, -0.611, 0.621]} scale={[1.176, 3.056, 1.176]} />
      <mesh geometry={nodes.Cylinder164.geometry} material={nodes.Cylinder164.material} type='MeshPhongMaterial' position={[80.18, 4.035, 54.601]} rotation={[-0.583, 0.605, 0.775]} scale={[2.381, 6.187, 2.381]} />
      <mesh geometry={nodes.Cylinder165.geometry} material={nodes.Cylinder165.material} type='MeshPhongMaterial' position={[87.081, 6.452, 59.657]} rotation={[0.27, -1.045, -0.081]} scale={[3.184, 8.272, 3.184]} />
      <mesh geometry={nodes.Cylinder166.geometry} material={nodes.Cylinder166.material} type='MeshPhongMaterial' position={[87.234, 4.1, 51.768]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder167.geometry} material={nodes.Cylinder167.material} type='MeshPhongMaterial' position={[81.716, 5.775, 43.945]} scale={[3.414, 7.268, 3.499]} />
      <mesh geometry={nodes.Cylinder168.geometry} material={nodes.Cylinder168.material} type='MeshPhongMaterial' position={[88.166, 5.424, 65.611]} rotation={[-0.294, -0.778, -0.091]} scale={[3.025, 7.86, 3.025]} />
      <mesh geometry={nodes.Cylinder169.geometry} material={nodes.Cylinder169.material} type='MeshPhongMaterial' position={[72.694, 9.782, 63.453]} rotation={[0.011, 0.555, -0.123]} scale={[4.104, 10.662, 4.104]} />
      <mesh geometry={nodes.Cylinder170.geometry} material={nodes.Cylinder170.material} type='MeshPhongMaterial' position={[87.051, 5.775, -97.666]} scale={[3.414, 7.268, 3.499]} />
      <mesh geometry={nodes.Cylinder171.geometry} material={nodes.Cylinder171.material} type='MeshPhongMaterial' position={[92.569, 4.1, -89.844]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder172.geometry} material={nodes.Cylinder172.material} type='MeshPhongMaterial' position={[92.415, 6.452, -81.955]} rotation={[0.27, -1.045, -0.081]} scale={[3.184, 8.272, 3.184]} />
      <mesh geometry={nodes.Cylinder173.geometry} material={nodes.Cylinder173.material} type='MeshPhongMaterial' position={[85.515, 4.035, -87.011]} rotation={[-0.583, 0.605, 0.775]} scale={[2.381, 6.187, 2.381]} />
      <mesh geometry={nodes.Cylinder174.geometry} material={nodes.Cylinder174.material} type='MeshPhongMaterial' position={[86.047, 9.782, -94.827]} rotation={[0.014, 0.712, 0.11]} scale={[3.594, 9.338, 3.594]} />
      <mesh geometry={nodes.Cylinder175.geometry} material={nodes.Cylinder175.material} type='MeshPhongMaterial' position={[2.732, 4.471, -102.718]} rotation={[-0.109, 0.125, 0.289]} scale={[2.74, 7.119, 2.74]} />
      <mesh geometry={nodes.Cylinder176.geometry} material={nodes.Cylinder176.material} type='MeshPhongMaterial' position={[11.082, 4.837, -104.448]} rotation={[0.386, -0.686, 0.325]} scale={[4.122, 10.709, 4.122]} />
      <mesh geometry={nodes.Cylinder177.geometry} material={nodes.Cylinder177.material} type='MeshPhongMaterial' position={[6.797, 3.251, -104.727]} rotation={[0.008, -0.106, 0.482]} scale={[2.579, 6.7, 2.579]} />
      <mesh geometry={nodes.Cylinder178.geometry} material={nodes.Cylinder178.material} type='MeshPhongMaterial' position={[2.222, 4.733, -91.783]} rotation={[-0.181, 0.068, -0.327]} scale={[2.802, 5.965, 2.872]} />
      <mesh geometry={nodes.Cylinder179.geometry} material={nodes.Cylinder179.material} type='MeshPhongMaterial' position={[62.263, 5.775, 88.363]} rotation={[0, -1.478, 0]} scale={[3.414, 7.268, 3.499]} />
      <mesh geometry={nodes.Cylinder180.geometry} material={nodes.Cylinder180.material} type='MeshPhongMaterial' position={[54.985, 4.1, 94.581]} rotation={[0, -1.478, 0]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder181.geometry} material={nodes.Cylinder181.material} type='MeshPhongMaterial' position={[51.511, 4.035, 87.819]} rotation={[-0.623, -0.683, -0.01]} scale={[2.381, 6.187, 2.381]} />
      <mesh geometry={nodes.Cylinder182.geometry} material={nodes.Cylinder182.material} type='MeshPhongMaterial' position={[59.343, 9.782, 87.627]} rotation={[0.015, -0.766, 0.129]} scale={[3.594, 9.338, 3.594]} />
      <mesh geometry={nodes.Cylinder183.geometry} material={nodes.Cylinder183.material} type='MeshPhongMaterial' position={[-119.071, 9.782, 34.165]} rotation={[0.011, -0.185, 0.121]} scale={[3.594, 9.338, 3.594]} />
      <mesh geometry={nodes.Cylinder184.geometry} material={nodes.Cylinder184.material} type='MeshPhongMaterial' position={[-125.513, 4.035, 38.624]} rotation={[-0.478, -0.183, 0.322]} scale={[2.381, 6.187, 2.381]} />
      <mesh geometry={nodes.Cylinder185.geometry} material={nodes.Cylinder185.material} type='MeshPhongMaterial' position={[-125.162, 6.452, 47.171]} rotation={[2.797, -1.162, 2.508]} scale={[3.184, 8.272, 3.184]} />
      <mesh geometry={nodes.Cylinder186.geometry} material={nodes.Cylinder186.material} type='MeshPhongMaterial' position={[-118.899, 4.1, 42.371]} rotation={[0, -0.897, 0]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder187.geometry} material={nodes.Cylinder187.material} type='MeshPhongMaterial' position={[-116.226, 5.775, 33.179]} rotation={[0, -0.897, 0]} scale={[3.414, 7.268, 3.499]} />
      <mesh geometry={nodes.Cylinder188.geometry} material={nodes.Cylinder188.material} type='MeshPhongMaterial' position={[-129.139, 5.424, 51.733]} rotation={[-2.11, -1.328, -2.005]} scale={[3.025, 7.86, 3.025]} />
      <mesh geometry={nodes.Cylinder189.geometry} material={nodes.Cylinder189.material} type='MeshPhongMaterial' position={[-103.136, 4.035, 51.765]} rotation={[-0.478, -0.183, 0.322]} scale={[2.381, 6.187, 2.381]} />
      <mesh geometry={nodes.Cylinder190.geometry} material={nodes.Cylinder190.material} type='MeshPhongMaterial' position={[107.317, 4.733, 48.951]} rotation={[-0.181, 0.068, -0.327]} scale={[2.802, 5.965, 2.872]} />
      <mesh geometry={nodes.Cylinder191.geometry} material={nodes.Cylinder191.material} type='MeshPhongMaterial' position={[108.335, 10.625, 44.542]} rotation={[-0.282, -0.534, -0.34]} scale={[3.446, 8.954, 3.446]} />
      <mesh geometry={nodes.Cylinder192.geometry} material={nodes.Cylinder192.material} type='MeshPhongMaterial' position={[104.667, 10.911, 51.618]} rotation={[-0.042, -1.195, 0.229]} scale={[3.062, 7.957, 3.062]} />
      <mesh geometry={nodes.Cylinder193.geometry} material={nodes.Cylinder193.material} type='MeshPhongMaterial' position={[130.511, 4.733, 46.515]} rotation={[-0.181, 0.068, -0.327]} scale={[2.802, 5.965, 2.872]} />
      <mesh geometry={nodes.Cylinder194.geometry} material={nodes.Cylinder194.material} type='MeshPhongMaterial' position={[106.653, 10.546, 37.32]} rotation={[-0.177, -1.08, 0.171]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder195.geometry} material={nodes.Cylinder195.material} type='MeshPhongMaterial' position={[119.434, 7.347, 45.262]} rotation={[0.186, -0.236, 0.394]} scale={[2.904, 7.546, 2.904]} />
      <mesh geometry={nodes.Cylinder196.geometry} material={nodes.Cylinder196.material} type='MeshPhongMaterial' position={[114.693, 10.546, 29.631]} rotation={[-0.418, 0.253, 0.239]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder197.geometry} material={nodes.Cylinder197.material} type='MeshPhongMaterial' position={[123.987, 5.304, 21.18]} rotation={[0.106, 0.305, 0.007]} scale={[2.081, 5.407, 2.081]} />
      <mesh geometry={nodes.Cylinder198.geometry} material={nodes.Cylinder198.material} type='MeshPhongMaterial' position={[-80.215, 4.387, -80.039]} rotation={[0.582, -1.239, 0.088]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Cylinder199.geometry} material={nodes.Cylinder199.material} type='MeshPhongMaterial' position={[-91.003, 5.302, -70.6]} rotation={[0.546, -1.004, 0.176]} scale={[2.128, 5.528, 2.128]} />
      <mesh geometry={nodes.Cylinder200.geometry} material={nodes.Cylinder200.material} type='MeshPhongMaterial' position={[-85.271, 2.709, -76.081]} rotation={[0.451, 0.838, -0.82]} scale={[2.411, 6.264, 2.411]} />
      <mesh geometry={nodes.Cylinder201.geometry} material={nodes.Cylinder201.material} type='MeshPhongMaterial' position={[-88.948, 4.387, -82.508]} rotation={[0.846, -0.887, 0.164]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Cylinder202.geometry} material={nodes.Cylinder202.material} type='MeshPhongMaterial' position={[-83.669, 3.093, -78.568]} rotation={[0.379, 0.143, -0.773]} scale={[-0.507, -1.317, -0.507]} />
      <mesh geometry={nodes.Cylinder203.geometry} material={nodes.Cylinder203.material} type='MeshPhongMaterial' position={[-85.844, 7.577, -66.909]} rotation={[-0.052, -0.425, 0.114]} scale={[3.7, 9.614, 3.7]} />
      <mesh geometry={nodes.Cylinder204.geometry} material={nodes.Cylinder204.material} type='MeshPhongMaterial' position={[-79.261, 8.142, -100.922]} rotation={[0.02, -0.88, -0.04]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder205.geometry} material={nodes.Cylinder205.material} type='MeshPhongMaterial' position={[-54.079, 4.237, -112.264]} rotation={[0.154, -0.355, 0.275]} scale={[-3.327, -7.083, -3.41]} />
      <mesh geometry={nodes.Cylinder206.geometry} material={nodes.Cylinder206.material} type='MeshPhongMaterial' position={[-78.092, 1.303, -133.461]} rotation={[1.829, 0.316, 1.227]} scale={[1.785, 1.685, 1.038]} />
      <mesh geometry={nodes.Cylinder207.geometry} material={nodes.Cylinder207.material} type='MeshPhongMaterial' position={[-78.092, 1.303, -131.896]} rotation={[0.122, 0.191, -0.263]} scale={[1.785, 1.685, 1.038]} />
      <mesh geometry={nodes.Cylinder208.geometry} material={nodes.Cylinder208.material} type='MeshPhongMaterial' position={[-75.069, 2.937, -120.858]} rotation={[0.122, 0.191, -0.263]} scale={[1.69, 3.598, 1.732]} />
      <mesh geometry={nodes.Cylinder209.geometry} material={nodes.Cylinder209.material} type='MeshPhongMaterial' position={[-60.394, 8.142, -109.328]} rotation={[-0.224, -0.148, 0.108]} scale={[4.31, 9.176, 4.417]} />
      <mesh geometry={nodes.Cylinder210.geometry} material={nodes.Cylinder210.material} type='MeshPhongMaterial' position={[-69.562, 4.1, -127.902]} scale={[2.429, 5.173, 2.49]} />
      <mesh geometry={nodes.Cylinder211.geometry} material={nodes.Cylinder211.material} type='MeshPhongMaterial' position={[-48.244, 8.583, -126.002]} rotation={[-1.398, -1.036, -1.116]} scale={[3.744, 9.729, 3.744]} />
      <mesh geometry={nodes.Cylinder212.geometry} material={nodes.Cylinder212.material} type='MeshPhongMaterial' position={[-17.399, 11.036, -96.272]} rotation={[-0.084, -0.466, -0.513]} scale={[5.481, 14.24, 5.481]} />
      <mesh geometry={nodes.Cylinder213.geometry} material={nodes.Cylinder213.material} type='MeshPhongMaterial' position={[-47.984, 3.918, -119.708]} rotation={[-0.066, -0.169, 0.595]} scale={[1.392, 3.616, 1.392]} />
      <mesh geometry={nodes.Cylinder214.geometry} material={nodes.Cylinder214.material} type='MeshPhongMaterial' position={[-42.106, 4.48, -120.293]} rotation={[-0.44, 0.73, -0.11]} scale={[1.151, 2.991, 1.151]} />
      <mesh geometry={nodes.Cylinder215.geometry} material={nodes.Cylinder215.material} type='MeshPhongMaterial' position={[-44.3, 2.081, -115.787]} rotation={[-0.543, -0.383, 0.376]} scale={[-0.566, -1.47, -0.566]} />
      <mesh geometry={nodes.Cylinder216.geometry} material={nodes.Cylinder216.material} type='MeshPhongMaterial' position={[63.514, 7.448, -67.353]} rotation={[-0.11, -0.548, -0.55]} scale={[3.204, 8.326, 3.204]} />
      <mesh geometry={nodes.Cylinder217.geometry} material={nodes.Cylinder217.material} type='MeshPhongMaterial' position={[65.613, 8.168, -58.38]} rotation={[-0.042, -1.195, 0.229]} scale={[2.679, 6.961, 2.679]} />
      <mesh geometry={nodes.Cylinder218.geometry} material={nodes.Cylinder218.material} type='MeshPhongMaterial' position={[73.353, 6.658, -53.74]} rotation={[-0.517, -1.296, -0.834]} scale={[2.904, 7.546, 2.904]} />
      <mesh geometry={nodes.Cylinder219.geometry} material={nodes.Cylinder219.material} type='MeshPhongMaterial' position={[68.823, 7.918, -64.571]} rotation={[-0.282, -0.534, -0.34]} scale={[3.015, 7.833, 3.015]} />
      <mesh geometry={nodes.Cylinder220.geometry} material={nodes.Cylinder220.material} type='MeshPhongMaterial' position={[69.206, 7.181, -52.796]} rotation={[-0.556, -0.78, 0.127]} scale={[1.922, 4.994, 1.922]} />
      <mesh geometry={nodes.Cylinder221.geometry} material={nodes.Cylinder221.material} type='MeshPhongMaterial' position={[68.727, 3.093, -93.433]} rotation={[0.379, 0.143, -0.773]} scale={[-0.507, -1.317, -0.507]} />
      <mesh geometry={nodes.Cylinder222.geometry} material={nodes.Cylinder222.material} type='MeshPhongMaterial' position={[63.447, 4.387, -97.372]} rotation={[0.846, -0.887, 0.164]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Cylinder223.geometry} material={nodes.Cylinder223.material} type='MeshPhongMaterial' position={[67.124, 2.709, -90.945]} rotation={[0.451, 0.838, -0.82]} scale={[2.411, 6.264, 2.411]} />
      <mesh geometry={nodes.Cylinder224.geometry} material={nodes.Cylinder224.material} type='MeshPhongMaterial' position={[72.181, 4.387, -94.904]} rotation={[0.582, -1.239, 0.088]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Icosphere036.geometry} material={nodes.Icosphere036.material} type='MeshPhongMaterial' position={[-6.583, 16.557, 75.873]} rotation={[0.457, -0.12, -0.06]} scale={[8.154, 20.695, 8.154]} />
      <mesh geometry={nodes.Cylinder225.geometry} material={nodes.Cylinder225.material} type='MeshPhongMaterial' position={[98.57, 10.546, 79.204]} rotation={[-0.559, -0.735, -0.269]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder226.geometry} material={nodes.Cylinder226.material} type='MeshPhongMaterial' position={[94.207, 7.347, 113.699]} rotation={[0.658, -1.273, 0.986]} scale={[2.904, 7.546, 2.904]} />
      <mesh geometry={nodes.Cylinder227.geometry} material={nodes.Cylinder227.material} type='MeshPhongMaterial' position={[95.377, 10.546, 98.697]} rotation={[-2.997, -0.958, -2.696]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder228.geometry} material={nodes.Cylinder228.material} type='MeshPhongMaterial' position={[81.769, 10.911, 103.513]} rotation={[-3.118, -0.853, -2.855]} scale={[3.062, 7.957, 3.062]} />
      <mesh geometry={nodes.Cylinder229.geometry} material={nodes.Cylinder229.material} type='MeshPhongMaterial' position={[89.739, 10.625, 103.514]} rotation={[-1.86, -1.318, -2.063]} scale={[3.446, 8.954, 3.446]} />
      <mesh geometry={nodes.Cylinder230.geometry} material={nodes.Cylinder230.material} type='MeshPhongMaterial' position={[85.356, 4.733, 104.639]} rotation={[-0.337, -0.998, -0.626]} scale={[2.802, 5.965, 2.872]} />
      <mesh geometry={nodes.Cylinder231.geometry} material={nodes.Cylinder231.material} type='MeshPhongMaterial' position={[-102.082, 10.546, -61.005]} rotation={[-0.418, 0.253, 0.239]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder232.geometry} material={nodes.Cylinder232.material} type='MeshPhongMaterial' position={[-115.882, 7.347, -52.174]} rotation={[0.186, -0.236, 0.394]} scale={[2.904, 7.546, 2.904]} />
      <mesh geometry={nodes.Cylinder233.geometry} material={nodes.Cylinder233.material} type='MeshPhongMaterial' position={[-124.856, 10.546, -60.355]} rotation={[-0.177, -1.08, 0.171]} scale={[4.001, 8.519, 4.101]} />
      <mesh geometry={nodes.Cylinder234.geometry} material={nodes.Cylinder234.material} type='MeshPhongMaterial' position={[-148.749, 10.911, -37.605]} rotation={[-0.042, -1.195, 0.229]} scale={[3.062, 7.957, 3.062]} />
      <mesh geometry={nodes.Cylinder235.geometry} material={nodes.Cylinder235.material} type='MeshPhongMaterial' position={[-126.98, 10.625, -52.894]} rotation={[-0.282, -0.534, -0.34]} scale={[3.446, 8.954, 3.446]} />
      <mesh geometry={nodes.Cylinder236.geometry} material={nodes.Cylinder236.material} type='MeshPhongMaterial' position={[-128.369, 4.733, -45.383]} rotation={[-0.181, 0.068, -0.327]} scale={[2.802, 5.965, 2.872]} />
      <mesh geometry={nodes.Cylinder237.geometry} material={nodes.Cylinder237.material} type='MeshPhongMaterial' position={[-137.69, 1.521, -29.722]} rotation={[0.453, 0.72, -0.548]} scale={[0.717, 1.863, 0.717]} />
      <mesh geometry={nodes.Cylinder238.geometry} material={nodes.Cylinder238.material} type='MeshPhongMaterial' position={[-36.403, 9.998, -101.542]} rotation={[0.655, -0.583, -0.682]} scale={[0.025, 0.01, 0.015]} />
      <mesh geometry={nodes.Cylinder239.geometry} material={nodes.Cylinder239.material} type='MeshPhongMaterial' position={[45.636, 2.742, 9.929]} rotation={[0.186, 0.009, -0.411]} scale={[1.174, 0.453, 0.696]} />
      <mesh geometry={nodes.Cylinder240.geometry} material={nodes.Cylinder240.material} type='MeshPhongMaterial' position={[77.905, -5.211, 16.808]} rotation={[0.082, 0.126, -0.823]} scale={[0.241, 0.093, 0.143]} />
      <mesh geometry={nodes.Cylinder241.geometry} material={nodes.Cylinder241.material} type='MeshPhongMaterial' position={[77.016, 3.71, 61.233]} rotation={[-0.028, 0.454, -1.275]} scale={[1.056, 0.407, 0.626]} />
      <mesh geometry={nodes.Cylinder242.geometry} material={nodes.Cylinder242.material} type='MeshPhongMaterial' position={[-62.177, 10.12, -6.959]} rotation={[0.474, -0.782, -1.026]} scale={[0.301, 0.116, 0.178]} />
      <mesh geometry={nodes.Cylinder243.geometry} material={nodes.Cylinder243.material} type='MeshPhongMaterial' position={[-44.459, -5.427, -109.206]} rotation={[-0.345, 0.195, 0.499]} scale={[0.099, 0.038, 0.059]} />
      <mesh geometry={nodes.Cylinder244.geometry} material={nodes.Cylinder244.material} type='MeshPhongMaterial' position={[87.073, 4.794, -20.039]} rotation={[-0.142, 0.122, 0.498]} scale={[0.877, 0.338, 0.52]} />
      <mesh geometry={nodes.Cylinder245.geometry} material={nodes.Cylinder245.material} type='MeshPhongMaterial' position={[-62.626, -0.05, -51.137]} rotation={[-0.456, -0.171, 0.524]} scale={[0.657, 0.253, 0.39]} />
      <mesh geometry={nodes.Cylinder246.geometry} material={nodes.Cylinder246.material} type='MeshPhongMaterial' position={[-49.226, -6.442, 31.484]} rotation={[-0.233, 0.147, -0.343]} scale={[0.375, 0.144, 0.222]} />
      <mesh geometry={nodes.Cylinder247.geometry} material={nodes.Cylinder247.material} type='MeshPhongMaterial' position={[39.541, -1.599, 39.293]} rotation={[-0.186, 0.266, -0.898]} scale={[0.186, 0.072, 0.11]} />
      <mesh geometry={nodes.Cylinder248.geometry} material={nodes.Cylinder248.material} type='MeshPhongMaterial' position={[52.292, -6.07, -86.491]} rotation={[0.476, 0.299, 0.056]} scale={[0.695, 0.268, 0.412]} />
      <mesh geometry={nodes.Cylinder249.geometry} material={nodes.Cylinder249.material} type='MeshPhongMaterial' position={[-34.776, -1.61, -3.633]} rotation={[-0.016, 0.27, 0.54]} scale={[0.154, 0.059, 0.091]} />
      <mesh geometry={nodes.Cylinder250.geometry} material={nodes.Cylinder250.material} type='MeshPhongMaterial' position={[-16.261, -5.17, -87.242]} rotation={[0.158, 0.086, -0.495]} scale={[0.916, 0.353, 0.543]} />
      <mesh geometry={nodes.Cylinder251.geometry} material={nodes.Cylinder251.material} type='MeshPhongMaterial' position={[34.537, 3.357, 79.896]} rotation={[0.059, -0.013, -1.182]} scale={[0.814, 0.314, 0.482]} />
      <mesh geometry={nodes.Cylinder252.geometry} material={nodes.Cylinder252.material} type='MeshPhongMaterial' position={[-10.944, 2.141, -6.863]} rotation={[-0.8, 0.361, -0.006]} scale={[0.525, 0.202, 0.311]} />
      <mesh geometry={nodes.Cylinder253.geometry} material={nodes.Cylinder253.material} type='MeshPhongMaterial' position={[-22.846, -3.193, -25.243]} rotation={[0.867, -0.402, -0.466]} scale={[0.889, 0.343, 0.527]} />
      <mesh geometry={nodes.Cylinder254.geometry} material={nodes.Cylinder254.material} type='MeshPhongMaterial' position={[-25.509, 0, 1.072]} rotation={[0.137, 0.044, -0.525]} scale={[0.836, 0.322, 0.496]} />
      <mesh geometry={nodes.Cylinder255.geometry} material={nodes.Cylinder255.material} type='MeshPhongMaterial' position={[62.884, -6.979, -107.134]} rotation={[0.243, 0.192, 0.434]} scale={[1.131, 0.436, 0.67]} />
      <mesh geometry={nodes.Cylinder256.geometry} material={nodes.Cylinder256.material} type='MeshPhongMaterial' position={[75.189, 5.881, -16.534]} rotation={[-0.372, -0.174, 0.595]} scale={[1.031, 0.397, 0.611]} />
      <mesh geometry={nodes.Cylinder257.geometry} material={nodes.Cylinder257.material} type='MeshPhongMaterial' position={[-37.893, -5.067, -86.327]} rotation={[0.582, 0.126, 0.115]} scale={[0.424, 0.163, 0.251]} />
      <mesh geometry={nodes.Cylinder258.geometry} material={nodes.Cylinder258.material} type='MeshPhongMaterial' position={[-97.429, -1.075, 18.054]} rotation={[-0.41, -0.13, 0.672]} scale={[0.875, 0.337, 0.519]} />
      <mesh geometry={nodes.Cylinder259.geometry} material={nodes.Cylinder259.material} type='MeshPhongMaterial' position={[-62.643, 4.579, 3.674]} rotation={[-0.207, 0.385, -1.03]} scale={[0.422, 0.163, 0.25]} />
      <mesh geometry={nodes.Cylinder260.geometry} material={nodes.Cylinder260.material} type='MeshPhongMaterial' position={[-68.164, 2.33, -87.384]} rotation={[-0.019, 0.14, -1.004]} scale={[0.895, 0.345, 0.53]} />
      <mesh geometry={nodes.Cylinder261.geometry} material={nodes.Cylinder261.material} type='MeshPhongMaterial' position={[-29.688, -3.664, -81.584]} rotation={[-0.633, 0.316, 0.075]} scale={[0.796, 0.307, 0.472]} />
      <mesh geometry={nodes.Cylinder262.geometry} material={nodes.Cylinder262.material} type='MeshPhongMaterial' position={[36.672, 4.591, -97.901]} rotation={[0.218, 0.494, 0.598]} scale={[0.803, 0.31, 0.476]} />
      <mesh geometry={nodes.Cylinder263.geometry} material={nodes.Cylinder263.material} type='MeshPhongMaterial' position={[98.485, -2.903, 69.797]} rotation={[-0.232, 0.426, -0.557]} scale={[0.792, 0.305, 0.469]} />
      <mesh geometry={nodes.Cylinder264.geometry} material={nodes.Cylinder264.material} type='MeshPhongMaterial' position={[46.679, -4.915, 52.435]} rotation={[-0.042, 0.24, -0.16]} scale={[1.138, 0.439, 0.675]} />
      <mesh geometry={nodes.Cylinder265.geometry} material={nodes.Cylinder265.material} type='MeshPhongMaterial' position={[3.998, -2.452, -38.406]} rotation={[0.347, -0.086, -0.992]} scale={[0.431, 0.166, 0.256]} />
      <mesh geometry={nodes.Cylinder266.geometry} material={nodes.Cylinder266.material} type='MeshPhongMaterial' position={[52.342, 10.455, 4.946]} rotation={[0.516, -0.006, -0.688]} scale={[0.373, 0.144, 0.221]} />
      <mesh geometry={nodes.Cylinder267.geometry} material={nodes.Cylinder267.material} type='MeshPhongMaterial' position={[-49.866, 4.035, 99.543]} rotation={[-0.251, 0.039, 0.648]} scale={[0.86, 0.332, 0.51]} />
      <mesh geometry={nodes.Cylinder268.geometry} material={nodes.Cylinder268.material} type='MeshPhongMaterial' position={[91.814, 1.757, 18.279]} rotation={[-0.311, 0.331, 0.211]} scale={[0.939, 0.362, 0.557]} />
      <mesh geometry={nodes.Cylinder269.geometry} material={nodes.Cylinder269.material} type='MeshPhongMaterial' position={[55.4, -8.98, -104.07]} rotation={[0.565, 0.438, -0.085]} scale={[0.679, 0.262, 0.402]} />
      <mesh geometry={nodes.Cylinder270.geometry} material={nodes.Cylinder270.material} type='MeshPhongMaterial' position={[-60.825, -6.911, 65.768]} rotation={[0.084, 0.139, 0.768]} scale={[0.806, 0.311, 0.478]} />
      <mesh geometry={nodes.Cylinder271.geometry} material={nodes.Cylinder271.material} type='MeshPhongMaterial' position={[70.634, 5.169, -84.85]} rotation={[0.558, 0.003, -0.153]} scale={[1.035, 0.399, 0.614]} />
      <mesh geometry={nodes.Cylinder272.geometry} material={nodes.Cylinder272.material} type='MeshPhongMaterial' position={[66.935, 9.403, 50.426]} rotation={[-0.359, -0.027, 0.458]} scale={[1.171, 0.451, 0.694]} />
      <mesh geometry={nodes.Cylinder273.geometry} material={nodes.Cylinder273.material} type='MeshPhongMaterial' position={[-28.804, 5.269, 17.916]} rotation={[-0.524, 0.694, -0.522]} scale={[0.058, 0.023, 0.035]} />
      <mesh geometry={nodes.Cylinder274.geometry} material={nodes.Cylinder274.material} type='MeshPhongMaterial' position={[62.373, 1.186, -81.656]} rotation={[0.751, -0.195, -0.505]} scale={[0.913, 0.352, 0.541]} />
      <mesh geometry={nodes.Cylinder275.geometry} material={nodes.Cylinder275.material} type='MeshPhongMaterial' position={[-26.52, -5.4, -18.876]} rotation={[-0.037, 0.15, -0.621]} scale={[0.631, 0.243, 0.374]} />
      <mesh geometry={nodes.Cylinder276.geometry} material={nodes.Cylinder276.material} type='MeshPhongMaterial' position={[14.299, -5.846, -23.415]} rotation={[0.374, -0.52, -0.924]} scale={[0.918, 0.354, 0.544]} />
      <mesh geometry={nodes.Cylinder277.geometry} material={nodes.Cylinder277.material} type='MeshPhongMaterial' position={[-48.72, -6.988, -32.824]} rotation={[0.074, -0.061, -1.211]} scale={[0.444, 0.171, 0.263]} />
      <mesh geometry={nodes.Cylinder278.geometry} material={nodes.Cylinder278.material} type='MeshPhongMaterial' position={[59.322, 6.535, 52.612]} rotation={[0.018, 0.333, 0.743]} scale={[0.522, 0.201, 0.309]} />
      <mesh geometry={nodes.Cylinder279.geometry} material={nodes.Cylinder279.material} type='MeshPhongMaterial' position={[-47.842, 4.35, -6.08]} rotation={[0.165, 0.189, 0.281]} scale={[0.736, 0.284, 0.436]} />
      <mesh geometry={nodes.Cylinder280.geometry} material={nodes.Cylinder280.material} type='MeshPhongMaterial' position={[-8.421, -2.866, -79.144]} rotation={[-0.011, 0.141, -1.275]} scale={[0.171, 0.066, 0.101]} />
      <mesh geometry={nodes.Cylinder281.geometry} material={nodes.Cylinder281.material} type='MeshPhongMaterial' position={[50.015, -3.491, -12.516]} rotation={[-0.232, 0.108, -0.254]} scale={[0.254, 0.098, 0.15]} />
      <mesh geometry={nodes.Cylinder282.geometry} material={nodes.Cylinder282.material} type='MeshPhongMaterial' position={[0.362, 1.35, 11.146]} rotation={[0.004, 0.203, 0.71]} scale={[0.532, 0.205, 0.315]} />
      <mesh geometry={nodes.Cylinder283.geometry} material={nodes.Cylinder283.material} type='MeshPhongMaterial' position={[-69.587, 9.164, -40.486]} rotation={[0.398, -0.176, -0.538]} scale={[0.113, 0.044, 0.067]} />
      <mesh geometry={nodes.Cylinder284.geometry} material={nodes.Cylinder284.material} type='MeshPhongMaterial' position={[-49.677, 6.827, 67.404]} rotation={[0.804, -0.128, -0.475]} scale={[1.111, 0.428, 0.658]} />
      <mesh geometry={nodes.Cylinder285.geometry} material={nodes.Cylinder285.material} type='MeshPhongMaterial' position={[-54.644, -3.464, -73.86]} rotation={[0.953, -0.096, -0.161]} scale={[0.173, 0.067, 0.103]} />
      <mesh geometry={nodes.Cylinder286.geometry} material={nodes.Cylinder286.material} type='MeshPhongMaterial' position={[81.887, -7.745, -55.131]} rotation={[0.357, -0.46, -1.141]} scale={[0.813, 0.313, 0.482]} />
      <mesh geometry={nodes.Cylinder287.geometry} material={nodes.Cylinder287.material} type='MeshPhongMaterial' position={[54.75, -10.255, 25.915]} rotation={[-0.443, 0.557, -0.372]} scale={[0.893, 0.344, 0.53]} />
      <mesh geometry={nodes.Cylinder288.geometry} material={nodes.Cylinder288.material} type='MeshPhongMaterial' position={[41.118, -4.673, -35.927]} rotation={[0.822, -0.369, -0.634]} scale={[0.514, 0.198, 0.305]} />
      <mesh geometry={nodes.Cylinder289.geometry} material={nodes.Cylinder289.material} type='MeshPhongMaterial' position={[108.515, -3.787, -23.796]} rotation={[0.949, 0.3, 0.087]} scale={[0.805, 0.31, 0.477]} />
      <mesh geometry={nodes.Cylinder290.geometry} material={nodes.Cylinder290.material} type='MeshPhongMaterial' position={[75.067, 0.32, -64.755]} rotation={[0.471, -0.356, -0.759]} scale={[0.307, 0.118, 0.182]} />
      <mesh geometry={nodes.Cylinder291.geometry} material={nodes.Cylinder291.material} type='MeshPhongMaterial' position={[82.064, -3.699, -51.003]} rotation={[-0.573, -0.071, 0.418]} scale={[0.057, 0.022, 0.034]} />
      <mesh geometry={nodes.Cylinder292.geometry} material={nodes.Cylinder292.material} type='MeshPhongMaterial' position={[58.903, -6.316, -19.367]} rotation={[-0.633, 0.602, -0.194]} scale={[0.809, 0.312, 0.48]} />
      <mesh geometry={nodes.Cylinder293.geometry} material={nodes.Cylinder293.material} type='MeshPhongMaterial' position={[104.458, 5.373, -43.515]} rotation={[0.876, 0.227, 0.038]} scale={[0.653, 0.252, 0.387]} />
      <mesh geometry={nodes.Cylinder294.geometry} material={nodes.Cylinder294.material} type='MeshPhongMaterial' position={[27.461, 3.609, -62.131]} rotation={[-0.319, 0.723, -0.963]} scale={[0.376, 0.145, 0.223]} />
      <mesh geometry={nodes.Cylinder295.geometry} material={nodes.Cylinder295.material} type='MeshPhongMaterial' position={[-38.71, 2.122, 25.132]} rotation={[0.672, -0.15, -0.367]} scale={[0.43, 0.166, 0.255]} />
      <mesh geometry={nodes.Cylinder296.geometry} material={nodes.Cylinder296.material} type='MeshPhongMaterial' position={[29.768, 3.398, 4.808]} rotation={[0.095, -0.261, -1.247]} scale={[0.126, 0.049, 0.075]} />
      <mesh geometry={nodes.Cylinder297.geometry} material={nodes.Cylinder297.material} type='MeshPhongMaterial' position={[8.746, -9.949, -86.594]} rotation={[0.072, 0.042, 0.21]} scale={[0.434, 0.167, 0.257]} />
      <mesh geometry={nodes.Cylinder298.geometry} material={nodes.Cylinder298.material} type='MeshPhongMaterial' position={[-47.558, 5.611, -29.151]} rotation={[-0.094, 0.146, -0.488]} scale={[0.395, 0.152, 0.234]} />
      <mesh geometry={nodes.Cylinder299.geometry} material={nodes.Cylinder299.material} type='MeshPhongMaterial' position={[64.323, -4.667, -44.925]} rotation={[-0.242, 0.32, -0.054]} scale={[0.393, 0.151, 0.233]} />
      <mesh geometry={nodes.Cylinder300.geometry} material={nodes.Cylinder300.material} type='MeshPhongMaterial' position={[110.524, -5.778, -63.125]} rotation={[-0.753, 0.502, -0.176]} scale={[0.563, 0.217, 0.334]} />
      <mesh geometry={nodes.Cylinder301.geometry} material={nodes.Cylinder301.material} type='MeshPhongMaterial' position={[105.927, -5.129, 13.601]} rotation={[-0.038, 0.326, -1.294]} scale={[0.032, 0.012, 0.019]} />
      <mesh geometry={nodes.Cylinder302.geometry} material={nodes.Cylinder302.material} type='MeshPhongMaterial' position={[-63.725, -0.339, -48.358]} rotation={[0.67, 0.47, 0.493]} scale={[0.246, 0.095, 0.146]} />
      <mesh geometry={nodes.Cylinder303.geometry} material={nodes.Cylinder303.material} type='MeshPhongMaterial' position={[99.007, -9.12, -32.436]} rotation={[0.069, -0.013, -1.244]} scale={[0.209, 0.081, 0.124]} />
      <mesh geometry={nodes.Cylinder304.geometry} material={nodes.Cylinder304.material} type='MeshPhongMaterial' position={[72.22, 3.061, -98.273]} rotation={[0.663, 0.059, -0.295]} scale={[1.092, 0.421, 0.647]} />
      <mesh geometry={nodes.Cylinder305.geometry} material={nodes.Cylinder305.material} type='MeshPhongMaterial' position={[18.457, 2.997, 74.177]} rotation={[0.054, 0.317, -0.092]} scale={[0.026, 0.01, 0.015]} />
      <mesh geometry={nodes.Cylinder306.geometry} material={nodes.Cylinder306.material} type='MeshPhongMaterial' position={[78.711, 8.626, -66.551]} rotation={[0.18, 0.327, 0.614]} scale={[0.448, 0.173, 0.266]} />
      <mesh geometry={nodes.Cylinder307.geometry} material={nodes.Cylinder307.material} type='MeshPhongMaterial' position={[-32.205, -5.082, -25.242]} rotation={[-0.723, 0.239, 0.255]} scale={[0.619, 0.239, 0.367]} />
      <mesh geometry={nodes.Cylinder308.geometry} material={nodes.Cylinder308.material} type='MeshPhongMaterial' position={[-23.695, 4.927, -15.236]} rotation={[0.072, -0.085, -1.095]} scale={[0.609, 0.235, 0.361]} />
      <mesh geometry={nodes.Cylinder309.geometry} material={nodes.Cylinder309.material} type='MeshPhongMaterial' position={[98.444, -3.005, 17.13]} rotation={[0.253, -0.492, -1.244]} scale={[0.084, 0.032, 0.05]} />
      <mesh geometry={nodes.Cylinder310.geometry} material={nodes.Cylinder310.material} type='MeshPhongMaterial' position={[60.404, -2.785, -30.374]} rotation={[0.844, 0.655, 0.302]} scale={[0.268, 0.103, 0.159]} />
      <mesh geometry={nodes.Cylinder311.geometry} material={nodes.Cylinder311.material} type='MeshPhongMaterial' position={[18.155, 0.528, 78.514]} rotation={[-0.319, 0.622, -0.702]} scale={[0.475, 0.183, 0.282]} />
      <mesh geometry={nodes.Cylinder312.geometry} material={nodes.Cylinder312.material} type='MeshPhongMaterial' position={[37.427, 2.127, 31.138]} rotation={[0.313, 0.103, -0.402]} scale={[0.654, 0.252, 0.388]} />
      <mesh geometry={nodes.Cylinder313.geometry} material={nodes.Cylinder313.material} type='MeshPhongMaterial' position={[80.583, -7.403, 25.019]} rotation={[0.178, 0.308, -0.572]} scale={[0.22, 0.085, 0.131]} />
      <mesh geometry={nodes.Cylinder314.geometry} material={nodes.Cylinder314.material} type='MeshPhongMaterial' position={[63.032, 0.706, 78.219]} rotation={[0.62, -0.696, -0.784]} scale={[0.676, 0.261, 0.401]} />
      <mesh geometry={nodes.Cylinder315.geometry} material={nodes.Cylinder315.material} type='MeshPhongMaterial' position={[47.97, -9.342, 82.107]} rotation={[-0.007, 0.303, 0.815]} scale={[0.289, 0.112, 0.171]} />
      <mesh geometry={nodes.Cylinder316.geometry} material={nodes.Cylinder316.material} type='MeshPhongMaterial' position={[96.164, 6.806, 57.394]} rotation={[0.466, 0.041, -0.57]} scale={[0.178, 0.069, 0.106]} />
      <mesh geometry={nodes.Cylinder317.geometry} material={nodes.Cylinder317.material} type='MeshPhongMaterial' position={[77.103, -10.213, 76.234]} rotation={[0.297, 0.373, 0.683]} scale={[0.42, 0.162, 0.249]} />
      <mesh geometry={nodes.Cylinder318.geometry} material={nodes.Cylinder318.material} type='MeshPhongMaterial' position={[57.686, -5.073, -93.793]} rotation={[0.221, 0.256, 0.604]} scale={[0.481, 0.185, 0.285]} />
      <mesh geometry={nodes.Cylinder319.geometry} material={nodes.Cylinder319.material} type='MeshPhongMaterial' position={[65.193, -1.563, 65.582]} rotation={[0.029, -0.058, -1.311]} scale={[0.469, 0.181, 0.278]} />
      <mesh geometry={nodes.Cylinder320.geometry} material={nodes.Cylinder320.material} type='MeshPhongMaterial' position={[44.712, -7.508, 35.658]} rotation={[0.345, -0.098, -1.003]} scale={[0.773, 0.298, 0.458]} />
      <mesh geometry={nodes.Cylinder321.geometry} material={nodes.Cylinder321.material} type='MeshPhongMaterial' position={[41.253, -9.785, 10.631]} rotation={[-0.29, 0.192, 0.726]} scale={[0.662, 0.255, 0.392]} />
      <mesh geometry={nodes.Cylinder322.geometry} material={nodes.Cylinder322.material} type='MeshPhongMaterial' position={[108.904, -5.521, -34.589]} rotation={[0.382, 0.206, 0.319]} scale={[1.088, 0.419, 0.645]} />
      <mesh geometry={nodes.Cylinder323.geometry} material={nodes.Cylinder323.material} type='MeshPhongMaterial' position={[89.494, -0.271, -40.901]} rotation={[0.46, -0.706, -1.047]} scale={[0.766, 0.295, 0.454]} />
      <mesh geometry={nodes.Cylinder324.geometry} material={nodes.Cylinder324.material} type='MeshPhongMaterial' position={[-24.808, -3.815, -16.155]} rotation={[-0.516, 0.054, 0.329]} scale={[0.266, 0.102, 0.157]} />
      <mesh geometry={nodes.Cylinder325.geometry} material={nodes.Cylinder325.material} type='MeshPhongMaterial' position={[-55.798, -6.13, 68.842]} rotation={[0.677, 0.602, 0.573]} scale={[0.939, 0.362, 0.556]} />
      <mesh geometry={nodes.Cylinder326.geometry} material={nodes.Cylinder326.material} type='MeshPhongMaterial' position={[12.947, 4.375, 81.999]} rotation={[1.034, 0.201, -0.252]} scale={[1.071, 0.413, 0.635]} />
      <mesh geometry={nodes.Cylinder327.geometry} material={nodes.Cylinder327.material} type='MeshPhongMaterial' position={[-54.637, -5.547, 7.208]} rotation={[0.533, 0.37, 0.433]} scale={[0.252, 0.097, 0.149]} />
      <mesh geometry={nodes.Cylinder328.geometry} material={nodes.Cylinder328.material} type='MeshPhongMaterial' position={[-81.575, -9.804, 45.472]} rotation={[-0.621, -0.216, 0.568]} scale={[0.07, 0.027, 0.041]} />
      <mesh geometry={nodes.Cylinder329.geometry} material={nodes.Cylinder329.material} type='MeshPhongMaterial' position={[62.944, -4.772, -69.873]} rotation={[0.069, 0.082, 0.59]} scale={[0.162, 0.063, 0.096]} />
      <mesh geometry={nodes.Cylinder330.geometry} material={nodes.Cylinder330.material} type='MeshPhongMaterial' position={[42.331, 3.902, 87.026]} rotation={[0.447, -0.308, -0.623]} scale={[0.706, 0.272, 0.418]} />
      <mesh geometry={nodes.Cylinder331.geometry} material={nodes.Cylinder331.material} type='MeshPhongMaterial' position={[-30.855, -1.656, -113.673]} rotation={[0.083, 0.17, -0.781]} scale={[0.599, 0.231, 0.355]} />
      <mesh geometry={nodes.Cylinder332.geometry} material={nodes.Cylinder332.material} type='MeshPhongMaterial' position={[92.022, 3.36, 47.304]} rotation={[0.758, -0.067, -0.614]} scale={[0.219, 0.084, 0.13]} />
      <mesh geometry={nodes.Cylinder333.geometry} material={nodes.Cylinder333.material} type='MeshPhongMaterial' position={[-64.805, -11.956, 16.315]} rotation={[0.831, 0.534, 0.156]} scale={[0.951, 0.367, 0.564]} />
      <mesh geometry={nodes.Cylinder334.geometry} material={nodes.Cylinder334.material} type='MeshPhongMaterial' position={[105.857, -5.166, -16.881]} rotation={[0.263, -0.001, -0.275]} scale={[0.955, 0.368, 0.566]} />
      <mesh geometry={nodes.Cylinder335.geometry} material={nodes.Cylinder335.material} type='MeshPhongMaterial' position={[-5.648, -3.955, -19.644]} rotation={[-0.028, 0.32, -0.401]} scale={[0.971, 0.374, 0.575]} />
      <mesh geometry={nodes.Cylinder336.geometry} material={nodes.Cylinder336.material} type='MeshPhongMaterial' position={[30.134, 4.758, -102.166]} rotation={[-0.398, -0.251, 0.638]} scale={[0.11, 0.043, 0.065]} />
      <mesh geometry={nodes.Icosphere065.geometry} material={nodes.Icosphere065.material} type='MeshPhongMaterial' position={[125.877, 7.532, -13.78]} rotation={[0.529, 0.553, -0.352]} scale={[4.538, 11.517, 4.538]} />
      <mesh geometry={nodes.Icosphere066.geometry} material={nodes.Icosphere066.material} type='MeshPhongMaterial' position={[-115.602, 18.5, -14.994]} rotation={[-0.362, -0.056, -0.756]} scale={[6.646, 16.867, 6.646]} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-41.821, 5.616, -59.808]} rotation={[0.799, -0.874, 0.214]} scale={[-0.756, -1.964, -0.756]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} type='MeshPhongMaterial' position={[-21.969, 8.675, 83.428]} rotation={[-0.327, -0.938, -0.488]} scale={[4.111, 10.682, 4.111]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} type='MeshPhongMaterial' position={[-22.251, 1.869, 39.59]} rotation={[-0.003, -0.052, -0.365]} scale={[0.157, 0.408, 0.157]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} type='MeshPhongMaterial' position={[-32.104, 7.195, 129.178]} rotation={[-0.602, 0.877, 0.017]} scale={[3.608, 9.374, 3.608]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} type='MeshPhongMaterial' position={[-51.909, 5.482, 43.587]} rotation={[0.597, -0.545, -0.368]} scale={[0.413, 1.074, 0.413]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} type='MeshPhongMaterial' position={[-51.458, 1.429, -60.158]} rotation={[-0.361, 0.562, 0.628]} scale={[-0.577, -1.499, -0.577]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} type='MeshPhongMaterial' position={[44.451, 7.577, 68.477]} rotation={[-0.052, -0.425, 0.114]} scale={[3.7, 9.614, 3.7]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} type='MeshPhongMaterial' position={[-75.092, 7.181, 3.1]} rotation={[-0.556, -0.78, 0.127]} scale={[1.922, 4.994, 1.922]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} type='MeshPhongMaterial' position={[-49.746, 1.328, 35.63]} rotation={[-0.368, -0.816, -0.359]} scale={[0.725, 1.883, 0.725]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} type='MeshPhongMaterial' position={[-21.947, 3, -10.411]} rotation={[-0.416, -0.885, -0.784]} scale={[-0.073, -0.191, -0.073]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} type='MeshPhongMaterial' position={[-72.161, 5.304, 29.491]} rotation={[0.106, 0.305, 0.007]} scale={[2.081, 5.407, 2.081]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} type='MeshPhongMaterial' position={[-32.842, 2.915, 36.734]} rotation={[-0.087, 0.265, 0.518]} scale={[-0.208, -0.54, -0.208]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} type='MeshPhongMaterial' position={[-75.475, 7.918, -8.674]} rotation={[-0.282, -0.534, -0.34]} scale={[3.015, 7.833, 3.015]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={nodes.Cylinder013.material} type='MeshPhongMaterial' position={[24.029, 5.469, 65.638]} rotation={[0.02, -0.506, -0.59]} scale={[2.923, 7.596, 2.923]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} type='MeshPhongMaterial' position={[-45.776, 3.402, 94.686]} rotation={[0.292, -0.356, -0.49]} scale={[1.363, 3.541, 1.363]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} type='MeshPhongMaterial' position={[-70.945, 6.658, 2.157]} rotation={[-0.517, -1.296, -0.834]} scale={[2.904, 7.546, 2.904]} />
      <mesh geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} type='MeshPhongMaterial' position={[-78.685, 8.168, -2.483]} rotation={[-0.042, -1.195, 0.229]} scale={[2.679, 6.961, 2.679]} />
      <mesh geometry={nodes.Cylinder017.geometry} material={nodes.Cylinder017.material} type='MeshPhongMaterial' position={[19.748, 8.175, 67.867]} rotation={[0.119, -0.746, 0.532]} scale={[3.928, 10.205, 3.928]} />
      <mesh geometry={nodes.Cylinder018.geometry} material={nodes.Cylinder018.material} type='MeshPhongMaterial' position={[-64.633, 8.949, -39.621]} rotation={[-0.632, -1.119, -0.719]} scale={[4.038, 10.492, 4.038]} />
      <mesh geometry={nodes.Cylinder019.geometry} material={nodes.Cylinder019.material} type='MeshPhongMaterial' position={[-27.161, 2.627, -68.089]} rotation={[0.459, -0.836, 0.621]} scale={[0.932, 2.422, 0.932]} />
      <mesh geometry={nodes.Cylinder020.geometry} material={nodes.Cylinder020.material} type='MeshPhongMaterial' position={[-31.25, 3.387, 57.92]} rotation={[0.008, -0.106, 0.482]} scale={[2.203, 5.724, 2.203]} />
      <mesh geometry={nodes.Cylinder021.geometry} material={nodes.Cylinder021.material} type='MeshPhongMaterial' position={[-31.738, 1.473, 43.622]} rotation={[-0.453, -0.805, -0.899]} scale={[0.785, 2.039, 0.785]} />
      <mesh geometry={nodes.Cylinder022.geometry} material={nodes.Cylinder022.material} type='MeshPhongMaterial' position={[-80.784, 7.448, -11.456]} rotation={[-0.11, -0.548, -0.55]} scale={[3.204, 8.326, 3.204]} />
      <mesh geometry={nodes.Cylinder023.geometry} material={nodes.Cylinder023.material} type='MeshPhongMaterial' position={[67.186, 6.016, 123.015]} rotation={[-0.602, 0.405, 0.718]} scale={[2.509, 6.519, 2.509]} />
      <mesh geometry={nodes.Cylinder024.geometry} material={nodes.Cylinder024.material} type='MeshPhongMaterial' position={[66.952, 9.782, -32.355]} rotation={[0.014, 0.712, 0.11]} scale={[3.594, 9.338, 3.594]} />
      <mesh geometry={nodes.Cylinder025.geometry} material={nodes.Cylinder025.material} type='MeshPhongMaterial' position={[-21.331, 4.081, 131.317]} rotation={[0.389, 0.647, -0.191]} scale={[2.491, 6.472, 2.491]} />
      <mesh geometry={nodes.Cylinder026.geometry} material={nodes.Cylinder026.material} type='MeshPhongMaterial' position={[-70.347, 7.03, 104.728]} rotation={[0.159, -0.228, -0.174]} scale={[3.35, 8.703, 3.35]} />
      <mesh geometry={nodes.Cylinder027.geometry} material={nodes.Cylinder027.material} type='MeshPhongMaterial' position={[-56.303, 2.604, -66.947]} rotation={[-0.257, 1.248, 0.348]} scale={[1.184, 3.076, 1.184]} />
      <mesh geometry={nodes.Cylinder028.geometry} material={nodes.Cylinder028.material} type='MeshPhongMaterial' position={[-60.96, 5.38, 13.551]} rotation={[0.453, 0.72, -0.548]} scale={[0.717, 1.863, 0.717]} />
      <mesh geometry={nodes.Cylinder029.geometry} material={nodes.Cylinder029.material} type='MeshPhongMaterial' position={[-88.277, 6.605, 91.231]} rotation={[0.181, -0.571, -0.082]} scale={[2.78, 7.223, 2.78]} />
      <mesh geometry={nodes.Cylinder030.geometry} material={nodes.Cylinder030.material} type='MeshPhongMaterial' position={[-0.256, 4.042, 147.39]} rotation={[0.436, 0.031, -0.182]} scale={[3.114, 8.092, 3.114]} />
      <mesh geometry={nodes.Cylinder031.geometry} material={nodes.Cylinder031.material} type='MeshPhongMaterial' position={[34.428, 2.954, 135.033]} rotation={[0.549, 1.067, -0.233]} scale={[1.439, 3.738, 1.439]} />
      <mesh geometry={nodes.Cylinder032.geometry} material={nodes.Cylinder032.material} type='MeshPhongMaterial' position={[-6.433, 3.753, 86.336]} rotation={[-2.053, -0.949, -1.864]} scale={[2.551, 6.627, 2.551]} />
      <mesh geometry={nodes.Cylinder033.geometry} material={nodes.Cylinder033.material} type='MeshPhongMaterial' position={[-46.936, 4.742, 53.125]} rotation={[0.386, -0.686, 0.325]} scale={[3.521, 9.149, 3.521]} />
      <mesh geometry={nodes.Cylinder034.geometry} material={nodes.Cylinder034.material} type='MeshPhongMaterial' position={[59.013, 6.03, 126.067]} rotation={[0.016, 0.109, -0.146]} scale={[3.229, 8.39, 3.229]} />
      <mesh geometry={nodes.Cylinder035.geometry} material={nodes.Cylinder035.material} type='MeshPhongMaterial' position={[113.014, 1.371, -44.856]} rotation={[-0.581, 0.678, 0]} scale={[-0.614, -1.595, -0.614]} />
      <mesh geometry={nodes.Cylinder036.geometry} material={nodes.Cylinder036.material} type='MeshPhongMaterial' position={[-30.281, 3.352, -82.377]} rotation={[0.277, 0.367, -0.298]} scale={[3.003, 7.801, 3.003]} />
      <mesh geometry={nodes.Cylinder037.geometry} material={nodes.Cylinder037.material} type='MeshPhongMaterial' position={[-61.425, 5.301, 10.289]} rotation={[-0.126, -0.499, -0.31]} scale={[1.812, 4.708, 1.812]} />
      <mesh geometry={nodes.Cylinder038.geometry} material={nodes.Cylinder038.material} type='MeshPhongMaterial' position={[28.635, 5.424, -82.698]} rotation={[-0.294, -0.778, -0.091]} scale={[3.025, 7.86, 3.025]} />
      <mesh geometry={nodes.Cylinder039.geometry} material={nodes.Cylinder039.material} type='MeshPhongMaterial' position={[-10.292, 2.113, -74.942]} rotation={[0.318, -0.104, -0.007]} scale={[1.02, 2.651, 1.02]} />
      <mesh geometry={nodes.Cylinder040.geometry} material={nodes.Cylinder040.material} type='MeshPhongMaterial' position={[8.236, 5.331, 60.555]} rotation={[-0.061, 0.472, 0.658]} scale={[1.348, 3.501, 1.348]} />
      <mesh geometry={nodes.Cylinder041.geometry} material={nodes.Cylinder041.material} type='MeshPhongMaterial' position={[-27.285, 5.057, 98.94]} rotation={[0.033, -0.432, 0.362]} scale={[2.256, 5.861, 2.256]} />
      <mesh geometry={nodes.Cylinder042.geometry} material={nodes.Cylinder042.material} type='MeshPhongMaterial' position={[-57.002, 2.984, 13.597]} rotation={[-0.101, -0.561, -0.719]} scale={[-0.136, -0.354, -0.136]} />
      <mesh geometry={nodes.Cylinder043.geometry} material={nodes.Cylinder043.material} type='MeshPhongMaterial' position={[32.918, 2.483, 31.264]} rotation={[-0.404, -0.907, -0.347]} scale={[0.213, 0.553, 0.213]} />
      <mesh geometry={nodes.Cylinder044.geometry} material={nodes.Cylinder044.material} type='MeshPhongMaterial' position={[16.373, 3.918, 54.537]} rotation={[-0.066, -0.169, 0.595]} scale={[1.392, 3.616, 1.392]} />
      <mesh geometry={nodes.Cylinder045.geometry} material={nodes.Cylinder045.material} type='MeshPhongMaterial' position={[-66.242, 5.45, 12.362]} rotation={[0.341, -0.835, 0.047]} scale={[-0.383, -0.995, -0.383]} />
      <mesh geometry={nodes.Cylinder046.geometry} material={nodes.Cylinder046.material} type='MeshPhongMaterial' position={[-65.312, 5.157, 98.082]} rotation={[0.527, 0.203, -0.244]} scale={[3.841, 9.979, 3.841]} />
      <mesh geometry={nodes.Cylinder047.geometry} material={nodes.Cylinder047.material} type='MeshPhongMaterial' position={[-8.952, 2.637, -42.618]} rotation={[0.72, -0.616, 0.519]} scale={[-0.128, -0.332, -0.128]} />
      <mesh geometry={nodes.Cylinder048.geometry} material={nodes.Cylinder048.material} type='MeshPhongMaterial' position={[-5.12, 7.063, -85.027]} rotation={[0.05, -0.271, 0.098]} scale={[3.582, 9.308, 3.582]} />
      <mesh geometry={nodes.Cylinder049.geometry} material={nodes.Cylinder049.material} type='MeshPhongMaterial' position={[2.727, 8.001, 128.499]} rotation={[-0.236, 0.708, -0.326]} scale={[2.921, 7.589, 2.921]} />
      <mesh geometry={nodes.Cylinder050.geometry} material={nodes.Cylinder050.material} type='MeshPhongMaterial' position={[-21.935, 3.22, 63.681]} rotation={[0.404, 0.161, -0.171]} scale={[1.316, 3.418, 1.316]} />
      <mesh geometry={nodes.Cylinder051.geometry} material={nodes.Cylinder051.material} type='MeshPhongMaterial' position={[-58.36, 4.537, -67.935]} rotation={[-0.055, -0.579, -0.098]} scale={[1.896, 4.927, 1.896]} />
      <mesh geometry={nodes.Cylinder052.geometry} material={nodes.Cylinder052.material} type='MeshPhongMaterial' position={[10.177, 4.182, 56.691]} rotation={[0.42, -0.605, -0.143]} scale={[0.439, 1.141, 0.439]} />
      <mesh geometry={nodes.Cylinder053.geometry} material={nodes.Cylinder053.material} type='MeshPhongMaterial' position={[11.309, 2.881, 56.737]} rotation={[-0.501, -0.387, 0.243]} scale={[-0.618, -1.606, -0.618]} />
      <mesh geometry={nodes.Cylinder054.geometry} material={nodes.Cylinder054.material} type='MeshPhongMaterial' position={[-4.031, 4.161, 113.799]} rotation={[0.142, 0.594, -0.559]} scale={[1.582, 3.717, 1.774]} />
      <mesh geometry={nodes.Cylinder055.geometry} material={nodes.Cylinder055.material} type='MeshPhongMaterial' position={[4.116, 4.984, 113.356]} rotation={[0.701, -1.265, 0.351]} scale={[1.902, 4.942, 1.902]} />
      <mesh geometry={nodes.Cylinder056.geometry} material={nodes.Cylinder056.material} type='MeshPhongMaterial' position={[17.149, 4.518, -52.661]} rotation={[-0.406, 0.291, -0.488]} scale={[0.729, 1.894, 0.729]} />
      <mesh geometry={nodes.Cylinder057.geometry} material={nodes.Cylinder057.material} type='MeshPhongMaterial' position={[-54.498, 4.119, -44.996]} rotation={[0.469, -0.52, 0.15]} scale={[0.96, 2.494, 0.96]} />
      <mesh geometry={nodes.Cylinder058.geometry} material={nodes.Cylinder058.material} type='MeshPhongMaterial' position={[36.569, 4.387, -38.013]} rotation={[0.22, -1.112, -0.457]} scale={[-0.326, -0.846, -0.326]} />
      <mesh geometry={nodes.Cylinder059.geometry} material={nodes.Cylinder059.material} type='MeshPhongMaterial' position={[6.906, 1.674, -67.275]} rotation={[-0.066, -1.065, 0.23]} scale={[0.975, 2.533, 0.975]} />
      <mesh geometry={nodes.Cylinder060.geometry} material={nodes.Cylinder060.material} type='MeshPhongMaterial' position={[-30.619, 1.932, 44.152]} rotation={[-0.191, -0.647, -0.285]} scale={[0.81, 2.105, 0.81]} />
      <mesh geometry={nodes.Cylinder061.geometry} material={nodes.Cylinder061.material} type='MeshPhongMaterial' position={[-69.979, 2.555, -8.617]} rotation={[-0.258, 0.388, 0.171]} scale={[0.802, 2.083, 0.802]} />
      <mesh geometry={nodes.Cylinder062.geometry} material={nodes.Cylinder062.material} type='MeshPhongMaterial' position={[-40.388, 2.558, 112.965]} rotation={[2.632, -1.191, 2.621]} scale={[1.521, 3.952, 1.521]} />
      <mesh geometry={nodes.Cylinder063.geometry} material={nodes.Cylinder063.material} type='MeshPhongMaterial' position={[41.188, 2.98, 42.175]} rotation={[-0.135, -0.033, -0.692]} scale={[-0.725, -1.883, -0.725]} />
      <mesh geometry={nodes.Cylinder064.geometry} material={nodes.Cylinder064.material} type='MeshPhongMaterial' position={[-52.269, 3.785, 15.544]} rotation={[0.514, -0.748, 0.991]} scale={[0.181, 0.471, 0.181]} />
      <mesh geometry={nodes.Cylinder065.geometry} material={nodes.Cylinder065.material} type='MeshPhongMaterial' position={[40.484, 1.63, -24.782]} rotation={[0.049, -0.215, -0.628]} scale={[0.025, 0.064, 0.025]} />
      <mesh geometry={nodes.Cylinder066.geometry} material={nodes.Cylinder066.material} type='MeshPhongMaterial' position={[-74.544, 8.353, -22.593]} rotation={[-0.122, -0.286, 0.045]} scale={[3.76, 9.771, 3.76]} />
      <mesh geometry={nodes.Cylinder067.geometry} material={nodes.Cylinder067.material} type='MeshPhongMaterial' position={[-4.231, 1.041, 47.615]} rotation={[-0.056, 0.532, 0.132]} scale={[-0.658, -1.711, -0.658]} />
      <mesh geometry={nodes.Cylinder068.geometry} material={nodes.Cylinder068.material} type='MeshPhongMaterial' position={[27.694, 3.707, -68.666]} rotation={[0.175, -0.703, 0.158]} scale={[1.61, 4.183, 1.61]} />
      <mesh geometry={nodes.Cylinder069.geometry} material={nodes.Cylinder069.material} type='MeshPhongMaterial' position={[33.482, 4.114, -65.75]} rotation={[-0.064, 0.303, 0.535]} scale={[1.761, 4.576, 1.761]} />
      <mesh geometry={nodes.Cylinder070.geometry} material={nodes.Cylinder070.material} type='MeshPhongMaterial' position={[-52.901, 5.356, 26.298]} rotation={[1.38, -1.141, 1.078]} scale={[4.258, 4.944, 3.855]} />
      <mesh geometry={nodes.Cylinder071.geometry} material={nodes.Cylinder071.material} type='MeshPhongMaterial' position={[46.627, 3.093, 56.819]} rotation={[0.379, 0.143, -0.773]} scale={[-0.507, -1.317, -0.507]} />
      <mesh geometry={nodes.Cylinder072.geometry} material={nodes.Cylinder072.material} type='MeshPhongMaterial' position={[-63.853, 3.416, -7.983]} rotation={[0.425, 0.231, 0.547]} scale={[0.275, 0.715, 0.275]} />
      <mesh geometry={nodes.Cylinder073.geometry} material={nodes.Cylinder073.material} type='MeshPhongMaterial' position={[22.251, 4.48, 53.952]} rotation={[-0.44, 0.73, -0.11]} scale={[1.151, 2.991, 1.151]} />
      <mesh geometry={nodes.Cylinder074.geometry} material={nodes.Cylinder074.material} type='MeshPhongMaterial' position={[37.21, 4.517, 44.079]} rotation={[0.141, 0.014, -0.074]} scale={[1.907, 4.954, 1.907]} />
      <mesh geometry={nodes.Cylinder075.geometry} material={nodes.Cylinder075.material} type='MeshPhongMaterial' position={[31.789, 2.181, 16.496]} rotation={[0.086, 0.993, -0.246]} scale={[0.071, 0.185, 0.071]} />
      <mesh geometry={nodes.Cylinder076.geometry} material={nodes.Cylinder076.material} type='MeshPhongMaterial' position={[41.347, 4.387, 52.879]} rotation={[0.846, -0.887, 0.164]} scale={[2, 5.197, 2]} />
      <mesh geometry={nodes.Cylinder077.geometry} material={nodes.Cylinder077.material} type='MeshPhongMaterial' position={[39.028, 1.632, 48.39]} rotation={[-0.077, 0.418, 0.703]} scale={[0.364, 0.945, 0.364]} />
      <mesh geometry={nodes.Cylinder078.geometry} material={nodes.Cylinder078.material} type='MeshPhongMaterial' position={[34.417, 5.482, 12.047]} rotation={[0.301, 0.437, -0.295]} scale={[-0.107, -0.278, -0.107]} />
      <mesh geometry={nodes.Cylinder079.geometry} material={nodes.Cylinder079.material} type='MeshPhongMaterial' position={[-61.765, 1.886, -9.907]} rotation={[0.157, -0.452, 0.71]} scale={[0.918, 2.385, 0.918]} />
      <mesh geometry={nodes.Cylinder080.geometry} material={nodes.Cylinder080.material} type='MeshPhongMaterial' position={[58.937, 3.083, -19.231]} rotation={[0.101, -0.611, 0.621]} scale={[1.176, 3.056, 1.176]} />
      <mesh geometry={nodes.Cylinder081.geometry} material={nodes.Cylinder081.material} type='MeshPhongMaterial' position={[36.014, 3.888, 61.091]} rotation={[-0.01, -0.924, -0.693]} scale={[1.124, 2.92, 1.124]} />
      <mesh geometry={nodes.Cylinder082.geometry} material={nodes.Cylinder082.material} type='MeshPhongMaterial' position={[45.024, 2.709, 59.306]} rotation={[0.451, 0.838, -0.82]} scale={[2.411, 6.264, 2.411]} />
      <mesh geometry={nodes.Cylinder083.geometry} material={nodes.Cylinder083.material} type='MeshPhongMaterial' position={[44.56, 2.137, 41.284]} rotation={[-0.416, 0.84, 0.901]} scale={[1.94, 5.04, 1.94]} />
      <mesh geometry={nodes.Cylinder084.geometry} material={nodes.Cylinder084.material} type='MeshPhongMaterial' position={[95.979, 8.583, 4.692]} rotation={[-1.398, -1.036, -1.116]} scale={[3.744, 9.729, 3.744]} />
      <mesh geometry={nodes.Cylinder085.geometry} material={nodes.Cylinder085.material} type='MeshPhongMaterial' position={[66.419, 4.035, -24.539]} rotation={[-0.583, 0.605, 0.775]} scale={[2.381, 6.187, 2.381]} />
      <mesh geometry={nodes.Cylinder086.geometry} material={nodes.Cylinder086.material} type='MeshPhongMaterial' position={[48.378, 3.141, -34.249]} rotation={[-0.427, -0.179, 0.267]} scale={[0.263, 0.684, 0.263]} />
      <mesh geometry={nodes.Cylinder087.geometry} material={nodes.Cylinder087.material} type='MeshPhongMaterial' position={[34.337, 6.394, 113.447]} rotation={[0.153, -0.778, 0.478]} scale={[3.112, 8.087, 3.112]} />
      <mesh geometry={nodes.Cylinder088.geometry} material={nodes.Cylinder088.material} type='MeshPhongMaterial' position={[51.955, 5.671, 14.682]} rotation={[-0.262, 0.124, 0.314]} scale={[3.674, 9.546, 3.674]} />
      <mesh geometry={nodes.Cylinder089.geometry} material={nodes.Cylinder089.material} type='MeshPhongMaterial' position={[43.006, 3.147, -48.962]} rotation={[0.328, -0.569, 0.71]} scale={[0.206, 0.535, 0.206]} />
      <mesh geometry={nodes.Cylinder090.geometry} material={nodes.Cylinder090.material} type='MeshPhongMaterial' position={[20.057, 2.081, 58.458]} rotation={[-0.543, -0.383, 0.376]} scale={[-0.566, -1.47, -0.566]} />
      <mesh geometry={nodes.Cylinder091.geometry} material={nodes.Cylinder091.material} type='MeshPhongMaterial' position={[42.344, 2.927, -1.193]} rotation={[-0.045, -1.019, 0.492]} scale={[-0.173, -0.451, -0.173]} />
      <mesh geometry={nodes.Cylinder092.geometry} material={nodes.Cylinder092.material} type='MeshPhongMaterial' position={[39.292, 5.302, 64.787]} rotation={[0.546, -1.004, 0.176]} scale={[2.128, 5.528, 2.128]} />
      <mesh geometry={nodes.Cylinder093.geometry} material={nodes.Cylinder093.material} type='MeshPhongMaterial' position={[-34.095, 3.922, -81.545]} rotation={[-0.007, 0.15, -0.334]} scale={[1.676, 4.355, 1.676]} />
      <mesh geometry={nodes.Cylinder094.geometry} material={nodes.Cylinder094.material} type='MeshPhongMaterial' position={[46.971, 5.09, 33.538]} rotation={[0.752, 0.786, -0.756]} scale={[0.066, 0.172, 0.066]} />
      <mesh geometry={nodes.Cylinder095.geometry} material={nodes.Cylinder095.material} type='MeshPhongMaterial' position={[107.603, 7.416, 3.766]} rotation={[1.104, 1.056, -0.786]} scale={[3.165, 8.223, 3.165]} />
      <mesh geometry={nodes.Cylinder096.geometry} material={nodes.Cylinder096.material} type='MeshPhongMaterial' position={[73.32, 6.452, -19.483]} rotation={[0.27, -1.045, -0.081]} scale={[3.184, 8.272, 3.184]} />
      <mesh geometry={nodes.Cylinder097.geometry} material={nodes.Cylinder097.material} type='MeshPhongMaterial' position={[-101.716, 6.734, 92.178]} rotation={[-0.115, 0.475, -0.058]} scale={[3.249, 8.441, 3.249]} />
      <mesh geometry={nodes.Cylinder098.geometry} material={nodes.Cylinder098.material} type='MeshPhongMaterial' position={[37.741, 5.263, -60.954]} rotation={[-0.688, -1.002, 0.021]} scale={[-0.394, -1.024, -0.394]} />
      <mesh geometry={nodes.Cylinder099.geometry} material={nodes.Cylinder099.material} type='MeshPhongMaterial' position={[42.945, 4.742, -62.621]} rotation={[-0.276, 0.066, 0.416]} scale={[0.459, 1.192, 0.459]} />
      <mesh geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} type='MeshPhongMaterial' position={[-94.351, 13.981, 106.253]} rotation={[0.49, -0.577, 0.378]} scale={[6.753, 17.141, 6.753]} />
      <mesh geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} type='MeshPhongMaterial' position={[-82.444, 16.079, 84.396]} rotation={[1.844, -1.164, 1.568]} scale={[7.18, 18.222, 7.18]} />
      <mesh geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} type='MeshPhongMaterial' position={[-95.626, 16.016, 50.865]} rotation={[-0.36, -0.092, -0.441]} scale={[7.202, 18.278, 7.202]} />
      <mesh geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} type='MeshPhongMaterial' position={[-106.534, 11.797, 26.035]} rotation={[0.636, -0.131, -0.026]} scale={[5.129, 13.018, 5.129]} />
      <mesh geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} type='MeshPhongMaterial' position={[-100.142, 14.943, -12.332]} rotation={[-0.507, -0.799, 0.144]} scale={[5.785, 14.683, 5.785]} />
      <mesh geometry={nodes.Icosphere006.geometry} material={nodes.Icosphere006.material} type='MeshPhongMaterial' position={[-115.602, 18.5, -26.713]} rotation={[0.29, 0.429, -0.018]} scale={[6.646, 16.867, 6.646]} />
      <mesh geometry={nodes.Icosphere007.geometry} material={nodes.Icosphere007.material} type='MeshPhongMaterial' position={[-128.242, 15.38, -29.705]} rotation={[1.373, -1.167, 1.425]} scale={[6.291, 15.967, 6.291]} />
      <mesh geometry={nodes.Icosphere008.geometry} material={nodes.Icosphere008.material} type='MeshPhongMaterial' position={[-77.634, 9.28, -96.087]} rotation={[1.871, -1.264, 1.651]} scale={[4.351, 11.043, 4.351]} />
      <mesh geometry={nodes.Icosphere009.geometry} material={nodes.Icosphere009.material} type='MeshPhongMaterial' position={[-66.214, 15.17, 75.598]} rotation={[-0.787, -0.689, -0.613]} scale={[6.747, 17.123, 6.747]} />
      <mesh geometry={nodes.Icosphere010.geometry} material={nodes.Icosphere010.material} type='MeshPhongMaterial' position={[-67.017, 13.311, 65.579]} rotation={[0.237, -1.081, 0.013]} scale={[6.514, 16.534, 6.514]} />
      <mesh geometry={nodes.Icosphere011.geometry} material={nodes.Icosphere011.material} type='MeshPhongMaterial' position={[-113.419, 14.461, 45.272]} rotation={[-0.011, 0.479, 0.452]} scale={[6.961, 17.668, 6.961]} />
      <mesh geometry={nodes.Icosphere012.geometry} material={nodes.Icosphere012.material} type='MeshPhongMaterial' position={[-96.435, 12.655, 30.795]} rotation={[0.307, 0.992, -0.084]} scale={[6.817, 17.302, 6.817]} />
      <mesh geometry={nodes.Icosphere013.geometry} material={nodes.Icosphere013.material} type='MeshPhongMaterial' position={[-122.594, 11.976, 4.684]} rotation={[-0.224, 0.689, 0.098]} scale={[7.089, 17.993, 7.089]} />
      <mesh geometry={nodes.Icosphere014.geometry} material={nodes.Icosphere014.material} type='MeshPhongMaterial' position={[-102.624, 15.286, -41.319]} rotation={[0.721, -1.111, 0.584]} scale={[7.039, 17.866, 7.039]} />
      <mesh geometry={nodes.Icosphere015.geometry} material={nodes.Icosphere015.material} type='MeshPhongMaterial' position={[-73.348, 15.255, -59.413]} rotation={[-0.017, -0.752, 0.116]} scale={[6.858, 17.405, 6.858]} />
      <mesh geometry={nodes.Icosphere016.geometry} material={nodes.Icosphere016.material} type='MeshPhongMaterial' position={[-10.672, 9.454, -83.614]} rotation={[-1.781, -1.379, -1.554]} scale={[5.733, 14.549, 5.733]} />
      <mesh geometry={nodes.Icosphere017.geometry} material={nodes.Icosphere017.material} type='MeshPhongMaterial' position={[-38.774, 17.264, 109.129]} rotation={[-1.242, -0.974, -1.522]} scale={[6.723, 17.064, 6.723]} />
      <mesh geometry={nodes.Icosphere018.geometry} material={nodes.Icosphere018.material} type='MeshPhongMaterial' position={[-56.813, 14.805, 66.011]} rotation={[-0.28, -0.856, -0.615]} scale={[5.749, 14.591, 5.749]} />
      <mesh geometry={nodes.Icosphere019.geometry} material={nodes.Icosphere019.material} type='MeshPhongMaterial' position={[-56.697, 20.145, 68.378]} rotation={[0.124, -1.032, 0.256]} scale={[6.537, 16.591, 6.537]} />
      <mesh geometry={nodes.Icosphere020.geometry} material={nodes.Icosphere020.material} type='MeshPhongMaterial' position={[-86.079, 8.777, -12.735]} rotation={[1.296, -1.33, 0.935]} scale={[5.185, 13.159, 5.185]} />
      <mesh geometry={nodes.Icosphere021.geometry} material={nodes.Icosphere021.material} type='MeshPhongMaterial' position={[-78.883, 10.697, -34.114]} rotation={[0.637, 0.894, -0.959]} scale={[6.329, 16.062, 6.329]} />
      <mesh geometry={nodes.Icosphere022.geometry} material={nodes.Icosphere022.material} type='MeshPhongMaterial' position={[-63.833, 17.767, -51.483]} rotation={[0.457, -0.12, -0.06]} scale={[8.154, 20.695, 8.154]} />
      <mesh geometry={nodes.Icosphere023.geometry} material={nodes.Icosphere023.material} type='MeshPhongMaterial' position={[-35.775, 14.661, -103.782]} rotation={[-0.581, 1.118, 0.47]} scale={[6.524, 16.559, 6.524]} />
      <mesh geometry={nodes.Icosphere024.geometry} material={nodes.Icosphere024.material} type='MeshPhongMaterial' position={[-31.531, 19.059, -117.495]} rotation={[-0.494, -1.178, -0.981]} scale={[6.872, 17.44, 6.872]} />
      <mesh geometry={nodes.Icosphere025.geometry} material={nodes.Icosphere025.material} type='MeshPhongMaterial' position={[-25.544, 14.954, 97.605]} rotation={[0.814, -1.114, 0.538]} scale={[6.201, 15.739, 6.201]} />
      <mesh geometry={nodes.Icosphere026.geometry} material={nodes.Icosphere026.material} type='MeshPhongMaterial' position={[-28.493, 16.169, 88.337]} rotation={[-0.417, 0.224, 0.126]} scale={[6.288, 15.96, 6.288]} />
      <mesh geometry={nodes.Icosphere027.geometry} material={nodes.Icosphere027.material} type='MeshPhongMaterial' position={[-37.136, 14.496, 61.739]} rotation={[-0.762, -1.371, -0.249]} scale={[6.539, 16.596, 6.539]} />
      <mesh geometry={nodes.Icosphere028.geometry} material={nodes.Icosphere028.material} type='MeshPhongMaterial' position={[90.129, 13.438, -21.485]} rotation={[0.127, 0.183, -0.175]} scale={[5.912, 15.005, 5.912]} />
      <mesh geometry={nodes.Icosphere029.geometry} material={nodes.Icosphere029.material} type='MeshPhongMaterial' position={[-94.929, 16.222, -89.211]} rotation={[-0.137, -0.182, -0.479]} scale={[6.453, 16.377, 6.453]} />
      <mesh geometry={nodes.Icosphere030.geometry} material={nodes.Icosphere030.material} type='MeshPhongMaterial' position={[4.054, 12.068, -98.59]} rotation={[-0.003, 0.98, -0.462]} scale={[5.863, 14.88, 5.863]} />
      <mesh geometry={nodes.Icosphere031.geometry} material={nodes.Icosphere031.material} type='MeshPhongMaterial' position={[-22.557, 17.162, -121.445]} rotation={[0.824, 1.341, -0.953]} scale={[7.174, 18.209, 7.174]} />
      <mesh geometry={nodes.Icosphere032.geometry} material={nodes.Icosphere032.material} type='MeshPhongMaterial' position={[-33.646, 13.166, -130.698]} rotation={[-0.206, -0.19, 0.073]} scale={[6.008, 15.249, 6.008]} />
      <mesh geometry={nodes.Icosphere033.geometry} material={nodes.Icosphere033.material} type='MeshPhongMaterial' position={[-10.076, 9.494, 94.355]} rotation={[0.54, 0.601, -0.667]} scale={[4.819, 12.231, 4.819]} />
      <mesh geometry={nodes.Icosphere034.geometry} material={nodes.Icosphere034.material} type='MeshPhongMaterial' position={[26.839, 13.518, 97.443]} rotation={[-0.19, 0.433, -0.248]} scale={[5.618, 14.259, 5.618]} />
      <mesh geometry={nodes.Icosphere035.geometry} material={nodes.Icosphere035.material} type='MeshPhongMaterial' position={[-56.873, 15.299, 113.167]} rotation={[-0.67, 0.535, 0.249]} scale={[6.95, 17.639, 6.95]} />
      <mesh geometry={nodes.Icosphere037.geometry} material={nodes.Icosphere037.material} type='MeshPhongMaterial' position={[-95.638, 17.417, -39.548]} rotation={[-0.39, 0.185, 0.546]} scale={[6.48, 16.446, 6.48]} />
      <mesh geometry={nodes.Icosphere038.geometry} material={nodes.Icosphere038.material} type='MeshPhongMaterial' position={[-24.558, 16.964, -102.267]} rotation={[0.235, 0.46, 0.112]} scale={[7.764, 19.705, 7.764]} />
      <mesh geometry={nodes.Icosphere039.geometry} material={nodes.Icosphere039.material} type='MeshPhongMaterial' position={[49.038, 14.31, -67.079]} rotation={[0.999, -1.08, 0.892]} scale={[6.714, 17.041, 6.714]} />
      <mesh geometry={nodes.Icosphere040.geometry} material={nodes.Icosphere040.material} type='MeshPhongMaterial' position={[53.849, 12.007, -106.95]} rotation={[-0.163, -0.893, 0.372]} scale={[6.611, 16.779, 6.611]} />
      <mesh geometry={nodes.Icosphere041.geometry} material={nodes.Icosphere041.material} type='MeshPhongMaterial' position={[34.733, 12.171, 94.066]} rotation={[0.43, 0.971, -0.404]} scale={[7.225, 18.337, 7.225]} />
      <mesh geometry={nodes.Icosphere042.geometry} material={nodes.Icosphere042.material} type='MeshPhongMaterial' position={[8.031, 16.075, 124.468]} rotation={[-0.531, 0.34, 0.67]} scale={[6.693, 16.988, 6.693]} />
      <mesh geometry={nodes.Icosphere043.geometry} material={nodes.Icosphere043.material} type='MeshPhongMaterial' position={[29.554, 14.107, 62.202]} rotation={[0.589, -0.822, 0.671]} scale={[6.446, 16.36, 6.446]} />
      <mesh geometry={nodes.Icosphere044.geometry} material={nodes.Icosphere044.material} type='MeshPhongMaterial' position={[127.424, 7.532, -32.364]} rotation={[-0.226, 0.26, -0.185]} scale={[4.538, 11.517, 4.538]} />
      <mesh geometry={nodes.Icosphere045.geometry} material={nodes.Icosphere045.material} type='MeshPhongMaterial' position={[102.084, 15.388, -53.776]} rotation={[-0.878, 1.059, 0.938]} scale={[7.139, 18.119, 7.139]} />
      <mesh geometry={nodes.Icosphere046.geometry} material={nodes.Icosphere046.material} type='MeshPhongMaterial' position={[58.358, 20.189, -39.786]} rotation={[0.799, -1.016, 0.688]} scale={[6.483, 16.454, 6.483]} />
      <mesh geometry={nodes.Icosphere047.geometry} material={nodes.Icosphere047.material} type='MeshPhongMaterial' position={[91.283, 19.694, -43.051]} rotation={[1.122, 0.949, -0.925]} scale={[7.715, 19.581, 7.715]} />
      <mesh geometry={nodes.Icosphere048.geometry} material={nodes.Icosphere048.material} type='MeshPhongMaterial' position={[32.206, 15.53, -117.697]} rotation={[2.306, -0.735, -0.708]} scale={[6.932, 17.595, 6.932]} />
      <mesh geometry={nodes.Icosphere049.geometry} material={nodes.Icosphere049.material} type='MeshPhongMaterial' position={[65.727, 15.477, 100.02]} rotation={[-0.037, -0.634, -0.315]} scale={[6.166, 15.649, 6.166]} />
      <mesh geometry={nodes.Icosphere050.geometry} material={nodes.Icosphere050.material} type='MeshPhongMaterial' position={[54.948, 15.227, 75.12]} rotation={[-0.4, 0.565, 0.619]} scale={[7.237, 18.367, 7.237]} />
      <mesh geometry={nodes.Icosphere051.geometry} material={nodes.Icosphere051.material} type='MeshPhongMaterial' position={[53.63, 17.958, 46.041]} rotation={[-0.673, -0.729, -0.388]} scale={[5.737, 14.56, 5.737]} />
      <mesh geometry={nodes.Icosphere052.geometry} material={nodes.Icosphere052.material} type='MeshPhongMaterial' position={[68.76, 17.103, 35.578]} rotation={[-0.516, -0.501, 0.07]} scale={[6.109, 15.505, 6.109]} />
      <mesh geometry={nodes.Icosphere053.geometry} material={nodes.Icosphere053.material} type='MeshPhongMaterial' position={[83.125, 12.969, -14.117]} rotation={[0.437, 0.416, -0.23]} scale={[6.099, 15.48, 6.099]} />
      <mesh geometry={nodes.Icosphere054.geometry} material={nodes.Icosphere054.material} type='MeshPhongMaterial' position={[53.63, 17.413, -34.676]} rotation={[0.107, 0.627, 0.455]} scale={[6.987, 17.733, 6.987]} />
      <mesh geometry={nodes.Icosphere055.geometry} material={nodes.Icosphere055.material} type='MeshPhongMaterial' position={[53.63, 14.51, -61.809]} rotation={[-0.878, -0.919, -0.761]} scale={[6.345, 16.105, 6.345]} />
      <mesh geometry={nodes.Icosphere056.geometry} material={nodes.Icosphere056.material} type='MeshPhongMaterial' position={[53.63, 18.056, -86.9]} rotation={[0.424, 0.317, -0.568]} scale={[6.151, 15.612, 6.151]} />
      <mesh geometry={nodes.Icosphere057.geometry} material={nodes.Icosphere057.material} type='MeshPhongMaterial' position={[68.997, 20.754, 81.028]} rotation={[-0.378, -0.813, 0.2]} scale={[7.246, 18.39, 7.246]} />
      <mesh geometry={nodes.Icosphere058.geometry} material={nodes.Icosphere058.material} type='MeshPhongMaterial' position={[79.026, 19.088, 71.924]} rotation={[-0.011, -0.837, -0.55]} scale={[6.102, 15.488, 6.102]} />
      <mesh geometry={nodes.Icosphere059.geometry} material={nodes.Icosphere059.material} type='MeshPhongMaterial' position={[89.478, 17.261, 36.682]} rotation={[0.086, 1.227, -0.384]} scale={[6.288, 15.959, 6.288]} />
      <mesh geometry={nodes.Icosphere060.geometry} material={nodes.Icosphere060.material} type='MeshPhongMaterial' position={[96.61, 15.335, 23.666]} rotation={[0.056, -0.126, -0.193]} scale={[7.277, 18.47, 7.277]} />
      <mesh geometry={nodes.Icosphere061.geometry} material={nodes.Icosphere061.material} type='MeshPhongMaterial' position={[126.805, 14.99, -2.612]} rotation={[-0.175, -0.608, -0.544]} scale={[7.228, 18.346, 7.228]} />
      <mesh geometry={nodes.Icosphere062.geometry} material={nodes.Icosphere062.material} type='MeshPhongMaterial' position={[79.026, 18.503, -32.665]} rotation={[0.447, -0.803, 0.078]} scale={[5.791, 14.697, 5.791]} />
      <mesh geometry={nodes.Icosphere063.geometry} material={nodes.Icosphere063.material} type='MeshPhongMaterial' position={[89.17, 13.395, -61.912]} rotation={[-0.062, 0.934, 0.537]} scale={[6.063, 15.389, 6.063]} />
      <mesh geometry={nodes.Icosphere064.geometry} material={nodes.Icosphere064.material} type='MeshPhongMaterial' position={[66.176, 14.425, -79.62]} rotation={[0.393, -0.856, -0.225]} scale={[9.464, 24.019, 9.464]} />
      
      <Crystal1 Cry={Cry}/>
      <Crystal2 Cry2={Cry2}/>
    </group>
      <CrystalP CryP={CryP} CryP1={CryP1} CryP2={CryP2} CryP3={CryP3} CryP4={CryP4} CryP5={CryP5} CryP6={CryP6} CryP7={CryP7} CryP8={CryP8} CryP9={CryP9} CryP10={CryP10} CryP11={CryP11} CryP12={CryP12} CryP13={CryP13}/>
      </group>
      </>
      )
}

useGLTF.preload('./Models/crystal_round.glb')
