/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/crystal_2.glb 
*/

import { useGLTF } from '@react-three/drei'
import React, { forwardRef } from 'react'

export const Crystal2 = forwardRef(function(props) {

  const { nodes, materials } = useGLTF('./Models/crystal_2.glb')



  return (
    <group {...props} ref={props.Cry2} position={[-70,7,14]} rotation={[0,0,0]} dispose={null}>
      <mesh geometry={nodes.Icosphere067.geometry} material={nodes.Icosphere067.material} scale={5.102} />
    </group>
  )
})

useGLTF.preload('./Models/crystal_2.glb')
