/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/crystal_parts.glb 
*/

import { useGLTF } from '@react-three/drei'
import React, { forwardRef } from 'react'

export const CrystalP = forwardRef(function(props) {

  const { nodes, materials } = useGLTF('./Models/crystal_parts.glb')
  return (
    <group {...props} ref={props.CryP} rotation={[3.2, 0, 0.9]} position={[0,25,115]} scale={[20,20,20]} dispose={null}>
      <mesh ref={props.CryP1} geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} />
      <mesh ref={props.CryP2} geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} />
      <mesh ref={props.CryP3} geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} />
      <mesh ref={props.CryP4} geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} />
      <mesh ref={props.CryP5} geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} />
      <mesh ref={props.CryP6} geometry={nodes.Icosphere006.geometry} material={nodes.Icosphere006.material} />
      <mesh ref={props.CryP7} geometry={nodes.Icosphere007.geometry} material={nodes.Icosphere007.material} />
      <mesh ref={props.CryP8} geometry={nodes.Icosphere008.geometry} material={nodes.Icosphere008.material} />
      <mesh ref={props.CryP9} geometry={nodes.Icosphere009.geometry} material={nodes.Icosphere009.material} />
      <mesh ref={props.CryP10} geometry={nodes.Icosphere010.geometry} material={nodes.Icosphere010.material} />
      <mesh ref={props.CryP11} geometry={nodes.Icosphere011.geometry} material={nodes.Icosphere011.material} />
      <mesh ref={props.CryP12} geometry={nodes.Icosphere012.geometry} material={nodes.Icosphere012.material} />
      <mesh ref={props.CryP13} geometry={nodes.Icosphere013.geometry} material={nodes.Icosphere013.material} />
    </group>
  )
})

useGLTF.preload('./Models/crystal_parts.glb')
